py_test(
 name = "tune_hvd_keras",
 size = "medium",
 srcs = ["tune_hvd_keras.py"],
 deps = ["//:ray_lib"],
 tags = ["team:ml", "compat", "exclusive"],
)

py_test(
 name = "tune_hvd_torch",
 size = "medium",
 srcs = ["tune_hvd_torch.py"],
 deps = ["//:ray_lib"],
 tags = ["team:ml", "compat", "exclusive"],
)
