// Copyright 2025 The Ray Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package api

import (
	"crypto/rand"
	"fmt"
	"sync/atomic"

	"github.com/ray-project/ray/go/pkg/errors"
	"github.com/ray-project/ray/go/pkg/ids"
)

// ObjectIDGenerator generates unique ObjectIDs for put operations.
// Consistent with Java's io.ray.runtime.object.ObjectIDGenerator
type ObjectIDGenerator struct {
	// driverID identifies the driver that created this generator.
	// ObjectIDs generated by different drivers are distinguished by this field.
	driverID ids.JobID
	// counter is an incremental counter used to generate unique task ID portions.
	// Each call to GenerateObjectID increments this counter.
	counter uint64
}

// NewObjectIDGenerator creates a new ObjectIDGenerator.
func NewObjectIDGenerator(driverID ids.JobID) *ObjectIDGenerator {
	return &ObjectIDGenerator{
		driverID: driverID,
		counter:  0,
	}
}

// GenerateObjectID generates a unique ObjectID.
// The generated ObjectID consists of:
// - A random task ID part (for uniqueness across tasks)
// - An incremental index (for uniqueness within a task)
func (g *ObjectIDGenerator) GenerateObjectID() (*ids.ObjectID, error) {
	// Generate random task ID part
	taskIDBytes := make([]byte, ids.TaskIDSize)
	if _, err := rand.Read(taskIDBytes); err != nil {
		return nil, fmt.Errorf("failed to generate random bytes: %w", err)
	}

	taskID, err := ids.TaskIDFromBinary(taskIDBytes)
	if err != nil {
		return nil, err
	}

	// Use counter to ensure unique ObjectID within a task
	// Start at 1: index 0 is reserved, ObjectIDFromIndex rejects indices < 1.
	index := int(atomic.AddUint64(&g.counter, 1))
	objectID := ids.ObjectIDFromIndex(taskID, ids.ObjectIDIndexType(index))

	return &objectID, nil
}

// GenerateObjectIDForTask generates an ObjectID for a specific task.
// This is useful when you need to create ObjectIDs with a known task ID.
func (g *ObjectIDGenerator) GenerateObjectIDForTask(taskID ids.TaskID, index int) *ids.ObjectID {
	objectID := ids.ObjectIDFromIndex(taskID, ids.ObjectIDIndexType(index))
	return &objectID
}

// globalObjectIDGenerator is the global ObjectID generator.
var globalObjectIDGenerator *ObjectIDGenerator

// initObjectIDGenerator initializes the global ObjectID generator.
func initObjectIDGenerator() error {
	handle, ok := tryGetHandle()
	if !ok || handle == nil {
		return errors.ErrRuntimeNotInitialized
	}

	runtime := handle.Runtime()
	if runtime == nil {
		return fmt.Errorf("runtime instance not available")
	}

	workerCtx := runtime.WorkerContext()
	if workerCtx == nil {
		return fmt.Errorf("worker context not available")
	}

	globalObjectIDGenerator = NewObjectIDGenerator(workerCtx.GetCurrentJobID())
	return nil
}

// generateObjectID uses the global generator to create an ObjectID.
func generateObjectID() (*ids.ObjectID, error) {
	if globalObjectIDGenerator == nil {
		if err := initObjectIDGenerator(); err != nil {
			return nil, err
		}
	}
	return globalObjectIDGenerator.GenerateObjectID()
}

// GenerateObjectIDForTask generates an ObjectID for a specific task.
// This is a convenience function that uses the global generator.
func GenerateObjectIDForTask(taskID ids.TaskID, index int) *ids.ObjectID {
	if globalObjectIDGenerator == nil {
		// If not initialized, just create a random ObjectID
		taskIDBytes := make([]byte, ids.TaskIDSize)
		if _, err := rand.Read(taskIDBytes); err != nil {
			// Fallback to zero task ID
			taskID = ids.NilTaskID()
		} else {
			taskID, _ = ids.TaskIDFromBinary(taskIDBytes)
		}
	}
	return globalObjectIDGenerator.GenerateObjectIDForTask(taskID, index)
}
