#!/usr/bin/env python3

import psutil
import time

def count_procs():
    count = 0
    for proc in psutil.process_iter(attrs=['name']):
        if proc.name().startswith('ray::'):
            count += 1
    return count

start_time = -1

last_count = -1
while True:
    try:
        count = count_procs()

        if start_time == -1 and count == 0:
            dur_s = 0
        elif start_time == -1 and count > 0:
            start_time = time.time()
        else:
            dur_s = time.time() - start_time

        if count != last_count:
            last_count = count
            print(f"{dur_s:.02f} {last_count}")
    except psutil.NoSuchProcess:
        pass
    time.sleep(0.01)
