group: release build
steps:
  - name: raycpubaseextra-testdeps
    label: "wanda: ray.py{{array.python}}.cpu.base-extra-testdeps"
    wanda: docker/base-extra-testdeps/cpu.wanda.yaml
    array:
      python:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    env:
      PYTHON_VERSION: "{{array.python}}"
      IMAGE_TYPE: "ray"
    depends_on:
      - raycpubaseextra(*)

  - name: raycudabaseextra-testdeps
    label: "wanda: ray.py{{array.python}}.cu{{array.cuda}}.base-extra-testdeps"
    wanda: docker/base-extra-testdeps/cuda.wanda.yaml
    array:
      python:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
      cuda:
        - "12.3.2-cudnn9"
      adjustments:
        - with:
            python: "3.12"
            cuda: "13.0.0-cudnn"
    env:
      PYTHON_VERSION: "{{array.python}}"
      CUDA_VERSION: "{{array.cuda}}"
      IMAGE_TYPE: "ray"
    depends_on:
      - raycudabaseextra(*)

  - name: ray-llmbaseextra-testdeps
    label: "wanda: ray.py{{array.python}}.llm.base-extra-testdeps (cuda {{array.cuda}})"
    wanda: docker/base-extra-testdeps/cuda.wanda.yaml
    array:
      python:
        - "3.12"
      cuda:
        - "13.0.0-cudnn"
      adjustments:
        - with:
            python: "3.11"
            cuda: "12.8.1-cudnn"
    env:
      PYTHON_VERSION: "{{array.python}}"
      CUDA_VERSION: "{{array.cuda}}"
      IMAGE_TYPE: "ray-llm"
    depends_on:
      - ray-llmbaseextra(*)

  - name: ray-mlcudabaseextra-testdeps
    label: "wanda: ray.py{{array.python}}.cu{{array.cuda}}.ml.base-extra-testdeps"
    wanda: docker/base-extra-testdeps/cuda.wanda.yaml
    array:
      python:
        - "3.10"
      cuda:
        - "12.1.1-cudnn8"
    env:
      PYTHON_VERSION: "{{array.python}}"
      CUDA_VERSION: "{{array.cuda}}"
      IMAGE_TYPE: "ray-ml"
    depends_on:
      - ray-mlcudabaseextra(*)

  - name: ray-anyscale-cpu-build
    label: "wanda: ray-anyscale py{{array.python}} cpu"
    wanda: ci/docker/ray-anyscale-cpu.wanda.yaml
    env_file: rayci.env
    array:
      python:
        # This list should be kept in sync with the list of supported Python in
        # release test suite
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    env:
      PYTHON_VERSION: "{{array.python}}"
      ARCH_SUFFIX: ""
    tags:
      - oss
    depends_on:
      - ray-wheel-build(*)
      - raycpubaseextra-testdeps($)

  - name: ray-anyscale-cuda-build
    label: "wanda: ray-anyscale py{{array.python}} {{array.platform}}"
    wanda: ci/docker/ray-anyscale-cuda.wanda.yaml
    env_file: rayci.env
    array:
      platform:
        - "cu12.3.2-cudnn9"
      python:
        # This list should be kept in sync with the list of supported Python in
        # release test suite
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
      adjustments:
        - with:
            python: "3.12"
            platform: "cu13.0.0-cudnn"
    env:
      PYTHON_VERSION: "{{array.python}}"
      PLATFORM: "{{array.platform}}"
      ARCH_SUFFIX: ""
    tags:
      - oss
    depends_on:
      - ray-wheel-build(*)
      - raycudabaseextra-testdeps($)

  - label: ":crane: publish: ray-anyscale py{{array.python}} {{array.platform}}"
    key: anyscalebuild
    instance_type: release-medium
    mount_buildkite_agent: true
    tags:
      - oss
    commands:
      - bazel run //ci/ray_ci/automation:push_release_test_image --
        --python-version {{array.python}}
        --platform {{array.platform}}
        --image-type ray
        --upload
    depends_on:
      - ray-anyscale-cpu-build($)
      - ray-anyscale-cuda-build($)
    array:
      platform:
        - cu12.3.2-cudnn9
        - cpu
      python:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
      adjustments:
        - with:
            python: "3.12"
            platform: cu13.0.0-cudnn

  - name: ray-llm-anyscale-cuda-build
    label: "wanda: ray-llm-anyscale py{{array.python}} {{array.platform}}"
    wanda: ci/docker/ray-llm-anyscale-cuda.wanda.yaml
    env_file: rayci.env
    array:
      platform:
        - "cu13.0.0-cudnn"
      python:
        - "3.12"
      adjustments:
        - with:
            python: "3.11"
            platform: "cu12.8.1-cudnn"
    env:
      PYTHON_VERSION: "{{array.python}}"
      PLATFORM: "{{array.platform}}"
      ARCH_SUFFIX: ""
    tags:
      - oss
    depends_on:
      - ray-wheel-build(*)
      - ray-llmbaseextra-testdeps($)

  - label: ":crane: publish: ray-llm-anyscale py{{array.python}} {{array.platform}}"
    key: anyscalellmbuild
    instance_type: release-medium
    mount_buildkite_agent: true
    tags:
      - oss
    commands:
      - bazel run //ci/ray_ci/automation:push_release_test_image --
        --python-version {{array.python}}
        --platform {{array.platform}}
        --image-type ray-llm
        --upload
    depends_on:
      - ray-llm-anyscale-cuda-build($)
    array:
      platform:
        - cu13.0.0-cudnn
      python:
        - "3.12"
      adjustments:
        - with:
            python: "3.11"
            platform: "cu12.8.1-cudnn"

  - name: ray-ml-anyscale-cuda-build
    label: "wanda: ray-ml-anyscale py{{array.python}} {{array.platform}}"
    wanda: ci/docker/ray-ml-anyscale-cuda.wanda.yaml
    env_file: rayci.env
    array:
      platform:
        - "cu12.1.1-cudnn8"
      python:
        # This list should be kept in sync with the list of supported Python in
        # release test suite
        - "3.10"
    env:
      PYTHON_VERSION: "{{array.python}}"
      PLATFORM: "{{array.platform}}"
      ARCH_SUFFIX: ""
    tags:
      - oss
    depends_on:
      - ray-wheel-build(*)
      - ray-mlcudabaseextra-testdeps($)

  - label: ":crane: publish: ray-ml-anyscale py{{array.python}} cu12.1.1-cudnn8"
    key: anyscalemlbuild
    instance_type: release-medium
    mount_buildkite_agent: true
    tags:
      - oss
    commands:
      - bazel run //ci/ray_ci/automation:push_release_test_image --
        --python-version {{array.python}}
        --platform cu12.1.1-cudnn8
        --image-type ray-ml
        --upload
    depends_on:
      - ray-ml-anyscale-cuda-build($)
    array:
      python:
        - "3.10"
