import copy
import json
import logging
import os
import subprocess
import tempfile
from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, List, Optional, Union

from ray.experimental.sandbox._internal.image_utils import (
    DEFAULT_IMAGES_DIR,
    pull_and_extract_container_image,
    sanitize_image_name,
)
from ray.experimental.sandbox.config import parse_memory_bytes

logger = logging.getLogger(__name__)

# The OCI capability sets a container process starts with. "ambient" is
# deliberately excluded: these are the sets Docker populates, and ambient
# capabilities would additionally survive into non-root execve'd children.
_OCI_CAPABILITY_SETS = ("bounding", "effective", "inheritable", "permitted")

_RESOLV_CONF = "/etc/resolv.conf"


def get_default_oci_spec() -> Dict[str, Any]:
    """Derive default OCI runtime specification by executing `runsc spec` in a temporary directory.

    Returns:
        Dictionary representation of the default OCI config.json generated by `runsc spec`.
    """
    with tempfile.TemporaryDirectory() as temp_dir:
        subprocess.run(["runsc", "spec"], cwd=temp_dir, check=True)
        config_path = os.path.join(temp_dir, "config.json")
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)


class BaseImageManager(ABC):
    """Abstract Base Class defining the contract for Container Image Managers.

    Image managers are responsible for acquiring container images (via registry pull,
    local archive extraction, or remote cache synchronization), providing metadata
    (such as working directory and environment variables), and generating standard OCI
    runtime specifications (bundles) for sandbox execution backends.
    """

    @abstractmethod
    def pull_image(
        self,
        image: str,
        timeout_seconds: float = 120.0,
    ) -> str:
        """Pull container image and extract rootfs into local cache or storage.

        Args:
            image: Container image reference (e.g. 'python:3.10-slim') or path to local tar archive.
            timeout_seconds: Timeout for network operations.

        Returns:
            Absolute directory path containing the extracted container filesystem.
        """
        pass

    @abstractmethod
    def get_image_dir(self, image: str) -> str:
        """Get the cached local directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute directory path for the image cache directory.
        """
        pass

    @abstractmethod
    def get_rootfs_path(self, image: str) -> str:
        """Get the rootfs directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute path to rootfs directory inside the image cache.
        """
        pass

    @abstractmethod
    def get_image_config(self, image: str) -> Dict[str, Any]:
        """Read and parse the container image configuration metadata.

        Args:
            image: Container image name or tar path.

        Returns:
            Dictionary representation of container image configuration.
        """
        pass

    @abstractmethod
    def get_workdir(self, image: str) -> Optional[str]:
        """Extract the default WorkingDir from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            Configured working directory string, or None if not specified.
        """
        pass

    @abstractmethod
    def get_envs(self, image: str) -> List[str]:
        """Extract the default environment variables list from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            List of 'KEY=VALUE' environment variable strings.
        """
        pass

    @abstractmethod
    def create_oci_spec(
        self,
        image: str,
        container_cwd: str = "/",
        workdir_path: Optional[str] = None,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        mount_workdir: bool = True,
        base_spec: Optional[Dict[str, Any]] = None,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> Dict[str, Any]:
        """Construct an OCI container configuration specification dictionary.

        Args:
            image: Container image name or tar path.
            container_cwd: Working directory inside the container.
            workdir_path: Host path to bind mount into container_cwd.
            env_dict: Optional environment variables dictionary overriding image envs.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Whether rootfs is mounted read-only.
            capabilities: Optional additional Linux capabilities unioned into the
                bounding/effective/inheritable/permitted sets (ambient untouched).
            network: runsc network mode the sandbox will run with; "host" drops
                the spec's empty network namespace and bind-mounts the host's
                resolv.conf so host networking works like Docker's.
            mount_workdir: If True (default), bind-mount ``workdir_path`` at
                the container cwd (shadowing image content there). False
                leaves the image filesystem untouched.
            base_spec: Optional base OCI spec dict to modify instead of generating a default.
            _oci_spec_transform_fn: Optional callback to transform the final spec.

        Returns:
            Dictionary matching the OCI runtime-spec schema (config.json).
        """
        pass

    @abstractmethod
    def prepare_oci_bundle(
        self,
        root_dir: str,
        workdir_path: str,
        container_cwd: str,
        image: str,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        mount_workdir: bool = True,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> str:
        """Prepare an OCI bundle directory containing config.json for a container instance.

        Args:
            root_dir: Host directory for the container bundle.
            workdir_path: Host directory for the sandbox working directory.
            container_cwd: Working directory inside container.
            image: Container image name or tar path.
            env_dict: Environment variables dictionary.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Read-only rootfs flag.
            capabilities: Optional additional Linux capabilities (see create_oci_spec).
            network: runsc network mode the sandbox will run with (see create_oci_spec).
            mount_workdir: Whether to bind-mount workdir_path at the container
                cwd (see create_oci_spec).
            _oci_spec_transform_fn: Optional OCI spec transform function.

        Returns:
            Path to the written config.json file.
        """
        pass


class ImageManager(BaseImageManager):
    """Manages container image downloading, caching, metadata inspection, and OCI bundle creation."""

    def __init__(self, images_dir: str = DEFAULT_IMAGES_DIR):
        self._images_dir = images_dir

    @property
    def images_dir(self) -> str:
        """Root directory for caching container images."""
        return self._images_dir

    def pull_image(
        self,
        image: str,
        timeout_seconds: float = 120.0,
    ) -> str:
        """Pull container image and extract rootfs into local images cache directory.

        Args:
            image: Container image name (e.g. 'busybox:latest') or path to local tar archive.
            timeout_seconds: Timeout for network operations.

        Returns:
            Absolute directory path containing the extracted container filesystem.
        """
        return pull_and_extract_container_image(
            image,
            images_dir=self._images_dir,
            timeout_seconds=timeout_seconds,
        )

    def get_image_dir(self, image: str) -> str:
        """Get the cached local directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute directory path for the image cache directory.
        """
        safe_name = sanitize_image_name(image)
        return os.path.join(self._images_dir, safe_name)

    def get_rootfs_path(self, image: str) -> str:
        """Get the rootfs directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute path to rootfs directory inside the image cache.
        """
        return os.path.join(self.get_image_dir(image), "rootfs")

    def is_image_extracted(self, image: str) -> bool:
        """Check if an image has already been extracted to the local cache.

        Args:
            image: Container image name or tar path.

        Returns:
            True if image directory exists and contains .extracted marker.
        """
        img_dir = self.get_image_dir(image)
        marker = os.path.join(img_dir, ".extracted")
        return os.path.isdir(img_dir) and os.path.exists(marker)

    def get_image_config(self, image: str) -> Dict[str, Any]:
        """Read and parse the image configuration JSON (.image_config.json) if available.

        Args:
            image: Container image name or tar path.

        Returns:
            Dictionary representation of container image configuration.
        """
        img_dir = self.get_image_dir(image)
        config_path = os.path.join(img_dir, ".image_config.json")
        if os.path.exists(config_path):
            try:
                with open(config_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as err:
                logger.warning(f"Failed to read image config at '{config_path}': {err}")
        return {}

    def get_workdir(self, image: str) -> Optional[str]:
        """Extract the default WorkingDir from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            Configured working directory string, or None if not specified.
        """
        cfg = self.get_image_config(image)
        return cfg.get("config", {}).get("WorkingDir")

    def get_envs(self, image: str) -> List[str]:
        """Extract the default environment variables list from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            List of 'KEY=VALUE' environment variable strings.
        """
        cfg = self.get_image_config(image)
        return cfg.get("config", {}).get("Env") or []

    def create_oci_spec(
        self,
        image: str,
        container_cwd: str = "/",
        workdir_path: Optional[str] = None,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        mount_workdir: bool = True,
        base_spec: Optional[Dict[str, Any]] = None,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> Dict[str, Any]:
        """Construct an OCI container configuration specification dictionary.

        Args:
            image: Container image name or tar path.
            container_cwd: Working directory inside the container.
            workdir_path: Host path to bind mount into container_cwd.
            env_dict: Optional environment variables dictionary overriding image envs.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Whether rootfs is mounted read-only.
            capabilities: Optional additional Linux capabilities unioned into the
                bounding/effective/inheritable/permitted sets (ambient untouched).
            network: runsc network mode the sandbox will run with; "host" drops
                the spec's empty network namespace and bind-mounts the host's
                resolv.conf so host networking works like Docker's.
            mount_workdir: If True (default), bind-mount ``workdir_path`` at
                the container cwd (shadowing image content there). False
                leaves the image filesystem untouched.
            base_spec: Optional base OCI spec dict to modify instead of generating a default.
            _oci_spec_transform_fn: Optional callback to transform the final spec.

        Returns:
            Dictionary matching the OCI runtime-spec schema (config.json).
        """
        spec = (
            copy.deepcopy(base_spec)
            if base_spec is not None
            else get_default_oci_spec()
        )

        image_dir = self.pull_image(image)
        rootfs = os.path.join(image_dir, "rootfs")

        spec.setdefault("root", {})
        spec["root"]["path"] = rootfs
        spec["root"]["readonly"] = readonly

        spec.setdefault("process", {})
        spec["process"]["args"] = ["sleep", "infinity"]
        spec["process"]["cwd"] = container_cwd

        # Inherit Env from image config by default
        envs = list(self.get_envs(image))

        # User-provided envs override image envs
        if env_dict:
            filtered_envs = []
            for e in envs:
                key = e.split("=", 1)[0]
                if key not in env_dict:
                    filtered_envs.append(e)
            envs = filtered_envs
            for k, v in env_dict.items():
                envs.append(f"{k}={v}")
        spec["process"]["env"] = envs

        if capabilities:
            # Defensive against caller-supplied base_spec: the key may exist
            # with a null value, which setdefault would hand straight back.
            caps = spec["process"].get("capabilities")
            if not isinstance(caps, dict):
                caps = {}
                spec["process"]["capabilities"] = caps
            for cap_set in _OCI_CAPABILITY_SETS:
                # Union rather than replace, so anything the runtime default
                # grants survives. Each set may also exist with a null value
                # in a caller-supplied base_spec.
                current = caps.get(cap_set)
                if not isinstance(current, list):
                    current = []
                caps[cap_set] = list(dict.fromkeys([*current, *capabilities]))

        # Set up default mounts
        mounts = spec.get("mounts", [])
        existing_dests = {m.get("destination") for m in mounts}

        if workdir_path and mount_workdir:
            default_binds = [
                (container_cwd, workdir_path),
            ]
            for dest, src in default_binds:
                if dest != "/" and dest not in existing_dests and os.path.exists(src):
                    mounts.append(
                        {
                            "destination": dest,
                            "type": "bind",
                            "source": src,
                            "options": [
                                "rbind",
                                "rw" if dest == container_cwd else "ro",
                            ],
                        }
                    )
                    existing_dests.add(dest)
        if network == "host":
            # A namespace entry with no "path" means "create a new, empty
            # namespace", and the default spec has one for "network". That
            # netns has nothing but loopback, which silently defeats runsc's
            # --network=host: the sandbox comes up with no route off the
            # host. Dropping the entry lets the container inherit the netns
            # runsc was launched in, which is what host networking means.
            linux_spec = spec.get("linux")
            if not isinstance(linux_spec, dict):
                linux_spec = {}
                spec["linux"] = linux_spec
            namespaces = linux_spec.get("namespaces")
            if isinstance(namespaces, list):
                linux_spec["namespaces"] = [
                    ns
                    for ns in namespaces
                    if not (
                        isinstance(ns, dict)
                        and ns.get("type") == "network"
                        and not ns.get("path")
                    )
                ]
            # Host networking shares the host's network stack but not its
            # resolver configuration, and most images ship an empty
            # /etc/resolv.conf because container engines inject one at run
            # time. Mirror Docker by bind-mounting the host's resolv.conf,
            # so DNS works out of the box (including on readonly rootfses).
            if os.path.exists(_RESOLV_CONF) and _RESOLV_CONF not in existing_dests:
                mounts.append(
                    {
                        "destination": _RESOLV_CONF,
                        "type": "bind",
                        "source": _RESOLV_CONF,
                        "options": ["rbind", "ro"],
                    }
                )

        spec["mounts"] = mounts

        # Configure OCI cgroup resource limits for CPU and memory
        linux_sec = spec.setdefault("linux", {})
        resources = linux_sec.setdefault("resources", {})

        if cpu is not None and cpu > 0:
            period = 100000
            quota = int(cpu * period)
            cpu_res = resources.setdefault("cpu", {})
            cpu_res["period"] = period
            cpu_res["quota"] = quota

        parsed_mem = parse_memory_bytes(memory)
        if parsed_mem is not None and parsed_mem > 0:
            mem_res = resources.setdefault("memory", {})
            mem_res["limit"] = parsed_mem

        if _oci_spec_transform_fn:
            result = _oci_spec_transform_fn(spec)
            if result is not None:
                spec = result

        return spec

    def prepare_oci_bundle(
        self,
        root_dir: str,
        workdir_path: str,
        container_cwd: str,
        image: str,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        mount_workdir: bool = True,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> str:
        """Prepare an OCI bundle directory containing config.json for a container instance.

        Args:
            root_dir: Host directory for the container bundle.
            workdir_path: Host directory for the sandbox working directory.
            container_cwd: Working directory inside container.
            image: Container image name or tar path.
            env_dict: Environment variables dictionary.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Read-only rootfs flag.
            capabilities: Optional additional Linux capabilities (see create_oci_spec).
            network: runsc network mode the sandbox will run with (see create_oci_spec).
            mount_workdir: Whether to bind-mount workdir_path at the container
                cwd (see create_oci_spec).
            _oci_spec_transform_fn: Optional OCI spec transform function.

        Returns:
            Path to the written config.json file.
        """
        config_json_path = os.path.join(root_dir, "config.json")
        rootfs_dir = os.path.join(root_dir, "rootfs")
        os.makedirs(rootfs_dir, exist_ok=True)

        spec = self.create_oci_spec(
            image=image,
            container_cwd=container_cwd,
            workdir_path=workdir_path,
            env_dict=env_dict,
            cpu=cpu,
            memory=memory,
            readonly=readonly,
            capabilities=capabilities,
            network=network,
            mount_workdir=mount_workdir,
            _oci_spec_transform_fn=_oci_spec_transform_fn,
        )

        config_json_str = json.dumps(spec, indent=2)
        with open(config_json_path, "w", encoding="utf-8") as f:
            f.write(config_json_str)

        return config_json_path
