import copy
import json
import logging
import os
import subprocess
import tempfile
from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, List, Optional, Union

from ray.experimental.sandbox._internal.image_utils import (
    DEFAULT_IMAGES_DIR,
    _release_image_use,
    pull_and_extract_container_image,
    sanitize_image_name,
)
from ray.experimental.sandbox.config import DEFAULT_PUBLIC_DNS, parse_memory_bytes

logger = logging.getLogger(__name__)

# The OCI capability sets written when `capabilities` is given (schema:
# https://github.com/opencontainers/runtime-spec/blob/main/config.md#linux-process).
# Modern Docker populates exactly these: "inheritable" was dropped by Docker
# for CVE-2022-24769, and "ambient" would survive into non-root execve'd
# children.
_OCI_CAPABILITY_SETS = ("bounding", "effective", "permitted")

_RESOLV_CONF = "/etc/resolv.conf"
_ETC_HOSTS = "/etc/hosts"


def get_default_oci_spec() -> Dict[str, Any]:
    """Derive default OCI runtime specification by executing `runsc spec` in a temporary directory.

    Returns:
        Dictionary representation of the default OCI config.json generated by `runsc spec`.
    """
    with tempfile.TemporaryDirectory() as temp_dir:
        subprocess.run(["runsc", "spec"], cwd=temp_dir, check=True)
        config_path = os.path.join(temp_dir, "config.json")
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)


class BaseImageManager(ABC):
    """Abstract Base Class defining the contract for Container Image Managers.

    Image managers are responsible for acquiring container images (via registry pull,
    local archive extraction, or remote cache synchronization), providing metadata
    (such as working directory and environment variables), and generating standard OCI
    runtime specifications (bundles) for sandbox execution backends.
    """

    @abstractmethod
    def pull_image(
        self,
        image: str,
        timeout_seconds: float = 120.0,
        instance_id: Optional[str] = None,
    ) -> str:
        """Pull container image and extract rootfs into local cache or storage.

        Args:
            image: Container image reference (e.g. 'python:3.10-slim') or path to local tar archive.
            timeout_seconds: Timeout for network operations.
            instance_id: The sandbox instance that will use the image. When
                given, the image is pinned in the cache until
                ``release_image`` is called for the same instance.

        Returns:
            Absolute directory path containing the extracted container filesystem.
        """
        pass

    def release_image(self, image: str, instance_id: str) -> None:
        """Release an instance's pin on an image taken by ``pull_image``.

        Managers without a cache need not override this.

        Args:
            image: Container image reference or tar path passed to ``pull_image``.
            instance_id: The sandbox instance that no longer uses the image.
        """
        return None

    @abstractmethod
    def get_image_dir(self, image: str) -> str:
        """Get the cached local directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute directory path for the image cache directory.
        """
        pass

    @abstractmethod
    def get_rootfs_path(self, image: str) -> str:
        """Get the rootfs directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute path to rootfs directory inside the image cache.
        """
        pass

    @abstractmethod
    def get_image_config(self, image: str) -> Dict[str, Any]:
        """Read and parse the container image configuration metadata.

        Args:
            image: Container image name or tar path.

        Returns:
            Dictionary representation of container image configuration.
        """
        pass

    @abstractmethod
    def get_workdir(self, image: str) -> Optional[str]:
        """Extract the default WorkingDir from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            Configured working directory string, or None if not specified.
        """
        pass

    @abstractmethod
    def get_envs(self, image: str) -> List[str]:
        """Extract the default environment variables list from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            List of 'KEY=VALUE' environment variable strings.
        """
        pass

    @abstractmethod
    def create_oci_spec(
        self,
        image: str,
        container_cwd: str = "/",
        workdir_path: Optional[str] = None,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        resolv_conf_source: Optional[str] = None,
        hosts_source: Optional[str] = None,
        base_spec: Optional[Dict[str, Any]] = None,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> Dict[str, Any]:
        """Construct an OCI container configuration specification dictionary.

        Args:
            image: Container image name or tar path.
            container_cwd: Working directory inside the container.
            workdir_path: Optional host directory to bind-mount read-write
                at container_cwd — the single writable path on a readonly
                rootfs. None mounts nothing.
            env_dict: Optional environment variables dictionary overriding image envs.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Whether rootfs is mounted read-only.
            capabilities: None keeps the runtime default; otherwise the
                bounding/effective/permitted sets are written exactly.
            network: Sandbox network mode; "host" and "public" drop the
                spec's empty network namespace.
            resolv_conf_source: Optional file to bind-mount read-only at
                /etc/resolv.conf.
            hosts_source: Optional file to bind-mount read-write at
                /etc/hosts (a per-sandbox copy, like the one container
                engines inject).
            base_spec: Optional base OCI spec dict to modify instead of generating a default.
            _oci_spec_transform_fn: Optional callback to transform the final spec.

        Returns:
            Dictionary matching the OCI runtime-spec schema (config.json).
        """
        pass

    @abstractmethod
    def prepare_oci_bundle(
        self,
        root_dir: str,
        workdir_path: str,
        container_cwd: str,
        image: str,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        dns: Optional[List[str]] = None,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> str:
        """Prepare an OCI bundle directory containing config.json for a container instance.

        Args:
            root_dir: Host directory for the container bundle.
            workdir_path: Optional host directory bind-mounted read-write at
                container_cwd (see create_oci_spec). None mounts nothing.
            container_cwd: Working directory inside container.
            image: Container image name or tar path.
            env_dict: Environment variables dictionary.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Read-only rootfs flag.
            capabilities: Optional additional Linux capabilities (see create_oci_spec).
            network: Sandbox network mode; picks the resolv.conf to mount
                ("public"/dns: generated, "host": the host's own).
            dns: Optional nameserver IPs for the generated resolv.conf.
            _oci_spec_transform_fn: Optional OCI spec transform function.

        Returns:
            Path to the written config.json file.
        """
        pass


class ImageManager(BaseImageManager):
    """Manages container image downloading, caching, metadata inspection, and OCI bundle creation."""

    def __init__(self, images_dir: str = DEFAULT_IMAGES_DIR):
        self._images_dir = images_dir

    @property
    def images_dir(self) -> str:
        """Root directory for caching container images."""
        return self._images_dir

    def pull_image(
        self,
        image: str,
        timeout_seconds: float = 120.0,
        instance_id: Optional[str] = None,
    ) -> str:
        """Pull container image and extract rootfs into local images cache directory.

        The cache is bounded (see ``RAY_SANDBOX_IMAGE_CACHE_MAX_BYTES``);
        passing ``instance_id`` pins the image until ``release_image``.

        Args:
            image: Container image name (e.g. 'busybox:latest') or path to local tar archive.
            timeout_seconds: Timeout for network operations.
            instance_id: The sandbox instance that will use the image.

        Returns:
            Absolute directory path containing the extracted container filesystem.
        """
        return pull_and_extract_container_image(
            image,
            images_dir=self._images_dir,
            timeout_seconds=timeout_seconds,
            instance_id=instance_id,
        )

    def release_image(self, image: str, instance_id: str) -> None:
        """Release an instance's pin on a cached image.

        Args:
            image: Container image name or tar path passed to ``pull_image``.
            instance_id: The sandbox instance that no longer uses the image.
        """
        _release_image_use(self.get_image_dir(image), instance_id)

    def get_image_dir(self, image: str) -> str:
        """Get the cached local directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute directory path for the image cache directory.
        """
        safe_name = sanitize_image_name(image)
        return os.path.join(self._images_dir, safe_name)

    def get_rootfs_path(self, image: str) -> str:
        """Get the rootfs directory path for an image.

        Args:
            image: Container image name or tar path.

        Returns:
            Absolute path to rootfs directory inside the image cache.
        """
        return os.path.join(self.get_image_dir(image), "rootfs")

    def is_image_extracted(self, image: str) -> bool:
        """Check if an image has already been extracted to the local cache.

        Args:
            image: Container image name or tar path.

        Returns:
            True if image directory exists and contains .extracted marker.
        """
        img_dir = self.get_image_dir(image)
        marker = os.path.join(img_dir, ".extracted")
        return os.path.isdir(img_dir) and os.path.exists(marker)

    def get_image_config(self, image: str) -> Dict[str, Any]:
        """Read and parse the image configuration JSON (.image_config.json) if available.

        Args:
            image: Container image name or tar path.

        Returns:
            Dictionary representation of container image configuration.
        """
        img_dir = self.get_image_dir(image)
        config_path = os.path.join(img_dir, ".image_config.json")
        if os.path.exists(config_path):
            try:
                with open(config_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as err:
                logger.warning(f"Failed to read image config at '{config_path}': {err}")
        return {}

    def get_workdir(self, image: str) -> Optional[str]:
        """Extract the default WorkingDir from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            Configured working directory string, or None if not specified.
        """
        cfg = self.get_image_config(image)
        return cfg.get("config", {}).get("WorkingDir")

    def get_envs(self, image: str) -> List[str]:
        """Extract the default environment variables list from the container image configuration.

        Args:
            image: Container image name or tar path.

        Returns:
            List of 'KEY=VALUE' environment variable strings.
        """
        cfg = self.get_image_config(image)
        return cfg.get("config", {}).get("Env") or []

    def create_oci_spec(
        self,
        image: str,
        container_cwd: str = "/",
        workdir_path: Optional[str] = None,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        resolv_conf_source: Optional[str] = None,
        hosts_source: Optional[str] = None,
        base_spec: Optional[Dict[str, Any]] = None,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> Dict[str, Any]:
        """Construct an OCI container configuration specification dictionary.

        Args:
            image: Container image name or tar path.
            container_cwd: Working directory inside the container.
            workdir_path: Optional host directory to bind-mount read-write
                at container_cwd — the single writable path on a readonly
                rootfs. None mounts nothing.
            env_dict: Optional environment variables dictionary overriding image envs.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Whether rootfs is mounted read-only.
            capabilities: None keeps the runtime default; otherwise the
                bounding/effective/permitted sets are written exactly.
            network: Sandbox network mode; "host" and "public" drop the
                spec's empty network namespace.
            resolv_conf_source: Optional file to bind-mount read-only at
                /etc/resolv.conf.
            hosts_source: Optional file to bind-mount read-write at
                /etc/hosts (a per-sandbox copy, like the one container
                engines inject).
            base_spec: Optional base OCI spec dict to modify instead of generating a default.
            _oci_spec_transform_fn: Optional callback to transform the final spec.

        Returns:
            Dictionary matching the OCI runtime-spec schema (config.json).
        """
        spec = (
            copy.deepcopy(base_spec)
            if base_spec is not None
            else get_default_oci_spec()
        )

        image_dir = self.pull_image(image)
        rootfs = os.path.join(image_dir, "rootfs")

        spec.setdefault("root", {})
        spec["root"]["path"] = rootfs
        spec["root"]["readonly"] = readonly

        # Docker parity: runsc mounts a private tmpfs over an *empty*
        # /tmp, breaking rename(2) from /tmp with EXDEV. The placeholder
        # keeps /tmp on the rootfs and stays visible in the sandbox (one
        # empty dotfile in scratch space); readonly sandboxes get a tmpfs
        # below, which hides it.
        tmp_dir = os.path.join(rootfs, "tmp")
        try:
            os.makedirs(tmp_dir, exist_ok=True)
            # Unconditional: /tmp must be world-writable with the sticky bit
            # whether it came from the image or was just created.
            os.chmod(tmp_dir, 0o1777)
            with open(
                os.path.join(tmp_dir, ".ray-sandbox-keep"), "a", encoding="utf-8"
            ):
                pass
        except OSError:
            # Best effort: runsc then falls back to its private tmpfs.
            pass

        spec.setdefault("process", {})
        spec["process"]["args"] = ["sleep", "infinity"]
        spec["process"]["cwd"] = container_cwd

        # Inherit Env from image config by default
        envs = list(self.get_envs(image))

        # User-provided envs override image envs
        if env_dict:
            filtered_envs = []
            for e in envs:
                key = e.split("=", 1)[0]
                if key not in env_dict:
                    filtered_envs.append(e)
            envs = filtered_envs
            for k, v in env_dict.items():
                envs.append(f"{k}={v}")
        spec["process"]["env"] = envs

        if capabilities is not None:
            # The key may exist with a null value in a caller-supplied base_spec.
            caps = spec["process"].get("capabilities")
            if not isinstance(caps, dict):
                caps = {}
                spec["process"]["capabilities"] = caps
            for cap_set in _OCI_CAPABILITY_SETS:
                # Written exactly (not unioned): [] runs with no capabilities.
                caps[cap_set] = list(dict.fromkeys(capabilities))

        # Set up default mounts
        mounts = spec.get("mounts", [])
        existing_dests = {m.get("destination") for m in mounts}

        if workdir_path:
            default_binds = [
                (container_cwd, workdir_path),
            ]
            for dest, src in default_binds:
                if dest != "/" and dest not in existing_dests and os.path.exists(src):
                    mounts.append(
                        {
                            "destination": dest,
                            "type": "bind",
                            "source": src,
                            "options": [
                                "rbind",
                                "rw" if dest == container_cwd else "ro",
                            ],
                        }
                    )
                    existing_dests.add(dest)
        if network in ("host", "public"):
            # The default spec carries an empty "network" namespace, which
            # would leave the sandbox loopback-only despite --network=host.
            # Drop it so the container inherits runsc's netns; a *pathed*
            # entry is somebody's explicit choice and is kept.
            linux_spec = spec.get("linux")
            if not isinstance(linux_spec, dict):
                linux_spec = {}
                spec["linux"] = linux_spec
            namespaces = linux_spec.get("namespaces")
            if isinstance(namespaces, list):
                linux_spec["namespaces"] = [
                    ns
                    for ns in namespaces
                    if not (
                        isinstance(ns, dict)
                        and ns.get("type") == "network"
                        and not ns.get("path")
                    )
                ]

        # Images usually ship an empty /etc/resolv.conf (container engines
        # inject one at run time); prepare_oci_bundle picks the file to mount.
        if resolv_conf_source and _RESOLV_CONF not in existing_dests:
            mounts.append(
                {
                    "destination": _RESOLV_CONF,
                    "type": "bind",
                    "source": resolv_conf_source,
                    "options": ["rbind", "ro"],
                }
            )
            existing_dests.add(_RESOLV_CONF)

        # Read-write like the file container engines inject; the source
        # is always a per-sandbox copy, never the node's own file.
        if hosts_source and _ETC_HOSTS not in existing_dests:
            mounts.append(
                {
                    "destination": _ETC_HOSTS,
                    "type": "bind",
                    "source": hosts_source,
                    "options": ["rbind", "rw"],
                }
            )
            existing_dests.add(_ETC_HOSTS)

        # Keep /tmp writable on a readonly rootfs, as it is under Docker.
        if readonly and "/tmp" not in existing_dests:
            mounts.append(
                {
                    "destination": "/tmp",
                    "type": "tmpfs",
                    "source": "tmpfs",
                    "options": ["nosuid", "nodev", "mode=1777"],
                }
            )
            existing_dests.add("/tmp")

        spec["mounts"] = mounts

        # Configure OCI cgroup resource limits for CPU and memory
        linux_sec = spec.setdefault("linux", {})
        resources = linux_sec.setdefault("resources", {})

        if cpu is not None and cpu > 0:
            period = 100000
            quota = int(cpu * period)
            cpu_res = resources.setdefault("cpu", {})
            cpu_res["period"] = period
            cpu_res["quota"] = quota

        parsed_mem = parse_memory_bytes(memory)
        if parsed_mem is not None and parsed_mem > 0:
            mem_res = resources.setdefault("memory", {})
            mem_res["limit"] = parsed_mem

        if _oci_spec_transform_fn:
            result = _oci_spec_transform_fn(spec)
            if result is not None:
                spec = result

        return spec

    def prepare_oci_bundle(
        self,
        root_dir: str,
        workdir_path: str,
        container_cwd: str,
        image: str,
        env_dict: Optional[Dict[str, str]] = None,
        cpu: Optional[float] = None,
        memory: Optional[Union[str, int, float]] = None,
        readonly: bool = True,
        capabilities: Optional[List[str]] = None,
        network: str = "none",
        dns: Optional[List[str]] = None,
        _oci_spec_transform_fn: Optional[Callable[[Dict], Optional[Dict]]] = None,
    ) -> str:
        """Prepare an OCI bundle directory containing config.json for a container instance.

        Args:
            root_dir: Host directory for the container bundle.
            workdir_path: Optional host directory bind-mounted read-write at
                container_cwd (see create_oci_spec). None mounts nothing.
            container_cwd: Working directory inside container.
            image: Container image name or tar path.
            env_dict: Environment variables dictionary.
            cpu: CPU core allocation.
            memory: Memory allocation specifier.
            readonly: Read-only rootfs flag.
            capabilities: Optional additional Linux capabilities (see create_oci_spec).
            network: Sandbox network mode; picks the resolv.conf to mount
                ("public"/dns: generated, "host": the host's own).
            dns: Optional nameserver IPs for the generated resolv.conf.
            _oci_spec_transform_fn: Optional OCI spec transform function.

        Returns:
            Path to the written config.json file.
        """
        config_json_path = os.path.join(root_dir, "config.json")
        rootfs_dir = os.path.join(root_dir, "rootfs")
        os.makedirs(rootfs_dir, exist_ok=True)

        resolv_conf_source: Optional[str] = None
        if network in ("public", "host"):
            nameservers = list(dns) if dns else None
            if network == "public" and nameservers is None:
                nameservers = list(DEFAULT_PUBLIC_DNS)
            if nameservers is not None:
                # Generated and host-independent: no search domains, resolver
                # VIPs, or ndots options leak in from the host.
                resolv_conf_source = os.path.join(root_dir, "resolv.conf")
                with open(resolv_conf_source, "w", encoding="utf-8") as f:
                    f.write("".join(f"nameserver {ip}\n" for ip in nameservers))
            elif os.path.exists(_RESOLV_CONF):
                resolv_conf_source = _RESOLV_CONF

        # Engines inject /etc/hosts at run time; without it `localhost`
        # does not resolve. Host networking also inherits the node's entries.
        hosts_source = os.path.join(root_dir, "hosts")
        host_entries = ""
        if network == "host" and os.path.exists(_ETC_HOSTS):
            try:
                with open(_ETC_HOSTS, "r", encoding="utf-8", errors="replace") as f:
                    host_entries = f.read()
            except OSError:
                host_entries = ""
        with open(hosts_source, "w", encoding="utf-8") as f:
            f.write("127.0.0.1\tlocalhost\n")
            f.write("::1\tlocalhost ip6-localhost ip6-loopback\n")
            if host_entries:
                f.write(host_entries)

        spec = self.create_oci_spec(
            image=image,
            container_cwd=container_cwd,
            workdir_path=workdir_path,
            env_dict=env_dict,
            cpu=cpu,
            memory=memory,
            readonly=readonly,
            capabilities=capabilities,
            network=network,
            resolv_conf_source=resolv_conf_source,
            hosts_source=hosts_source,
            _oci_spec_transform_fn=_oci_spec_transform_fn,
        )

        config_json_str = json.dumps(spec, indent=2)
        with open(config_json_path, "w", encoding="utf-8") as f:
            f.write(config_json_str)

        return config_json_path
