#!/usr/bin/env python3

import os
import ray

@ray.remote
class Actor:
    def abort(self):
        os.abort()

    def create(self):
        return os.getpid()
        

a = Actor.remote()

ray.get(a.create.remote())
input('waiting')
ray.get(a.abort.remote())
