# Examples

py_test(
    name = "example_es_cartpole_v1",
    size = "large",
    srcs = ["examples/es_cartpole_v1.py"],
    args = ["--run-as-test"],
    main = "es_cartpole_v1.py",
    tags = [
        "example",
        "team:rllib",
    ],
)

# Learning Tests

# Compilation Tests

py_test(
    name = "test_es",
    size = "large",
    srcs = ["tests/test_es.py"],
    tags = [
        "algorithms_dir",
        "team:rllib",
    ],
)
