# Examples

py_test(
    name = "example_es_cartpole_v1",
    main = "es_cartpole_v1.py",
    tags = ["team:rllib", "example"],
    size = "large",
    srcs = ["examples/es_cartpole_v1.py"],
    args = ["--run-as-test"]
)

# Learning Tests

# Compilation Tests

py_test(
    name = "test_es",
    tags = ["team:rllib", "algorithms_dir"],
    size = "large",
    srcs = ["tests/test_es.py"]
)
