py_library(
    name = "serve_doc_code",
    srcs = glob(["**/*.py"]),
    visibility = [
        "//doc:__subpackages__",
        "//python/ray/serve:__subpackages__",
        "//python/ray/serve:__pkg__"
    ],
)
