name: "ray-torch-py$PYTHON_VERSION-cu$CUDA_VERSION-base"
froms: ["cr.ray.io/rayproject/ray-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra"]
dockerfile: docker/ray-torch/Dockerfile
srcs:
  - python/deplocks/ray-torch/ray-torch-cu130_base_py$PYTHON_VERSION.lock
build_args:
  - FULL_BASE_IMAGE=cr.ray.io/rayproject/ray-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra
  - IMAGE_TYPE
tags:
  - cr.ray.io/rayproject/ray-torch-py$PYTHON_VERSION-cu$CUDA_VERSION-base
