applications:
  - args:
      prefill_config: &config
        model_loading_config:
          model_id: RedHatAI/Qwen3.5-9B-quantized.w4a16
        accelerator_type: A10G
        engine_kwargs:
          max_model_len: 8192
          language_model_only: true
          tensor_parallel_size: 1
          enforce_eager: false
          kv_transfer_config:
            kv_connector: NixlConnector
            kv_role: kv_both
        runtime_env:
          env_vars:
            VLLM_SSM_CONV_STATE_LAYOUT: DS
      decode_config: *config
    import_path: ray.serve.llm:build_pd_openai_app
    name: llm-endpoint
    route_prefix: /
