# Start with an Anyscale base image.
# Use the drop-down above to browse through all available images.
FROM anyscale/ray-llm:2.50.0-py311-cu128

RUN python3 -m pip install --no-cache-dir \
    "xgrammar==0.1.11" \
    "pynvml==12.0.0" \
    "hf_transfer==0.1.9" \
    "tensorboard==2.19.0" \
    "llamafactory>=0.9.3" \
    "transformers==4.45.2"

# Fast upload/download
ENV HF_HUB_ENABLE_HF_TRANSFER=1
