package org.ray.format.gcs;
// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ClassTableData extends Table {
  public static ClassTableData getRootAsClassTableData(ByteBuffer _bb) { return getRootAsClassTableData(_bb, new ClassTableData()); }
  public static ClassTableData getRootAsClassTableData(ByteBuffer _bb, ClassTableData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ClassTableData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startClassTableData(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endClassTableData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

