package org.ray.format.gcs;
// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CustomSerializerData extends Table {
  public static CustomSerializerData getRootAsCustomSerializerData(ByteBuffer _bb) { return getRootAsCustomSerializerData(_bb, new CustomSerializerData()); }
  public static CustomSerializerData getRootAsCustomSerializerData(ByteBuffer _bb, CustomSerializerData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public CustomSerializerData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startCustomSerializerData(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endCustomSerializerData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

