#!/bin/bash

# Set image type based on build argument
if [ $DOCKER_TAG = "cpu" ]; then
    docker build . --cache-from rayproject/ray:2.2.0-py38-cpu -t jcoffi/cluster-anywhere:cpu --build-arg IMAGETYPE=cpu
elif [ $DOCKER_TAG = "gpu" ]; then
    docker build . --cache-from rayproject/ray:2.2.0-py38-gpu -t jcoffi/cluster-anywhere:gpu --build-arg IMAGETYPE=gpu
else
    docker build . --cache-from rayproject/ray:2.2.0-py38-$DOCKER_TAG -t rayproject/ray:2.2.0-py38-$DOCKER_TAG --build-arg IMAGETYPE=$DOCKER_TAG
fi
