load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "gcs",
    srcs = [
        "client.go",
        "doc.go",
        "interfaces.go",
        "options.go",
        "state.go",
        "subscriber.go",
        "types.go",
    ],
    importpath = "github.com/ray-project/ray/go/pkg/gcs",
    visibility = ["//visibility:public"],
    deps = [
        "//go/pkg/ids",
        "//go/proto",
    ],
)
