# config.yaml
applications:
  - name: llm-direct-streaming
    route_prefix: /
    import_path: ray.serve.llm:build_openai_app
    args:
      llm_configs:
        - model_loading_config:
            model_id: qwen3.5-0.8b
            model_source: Qwen/Qwen3.5-0.8B
          deployment_config:
            autoscaling_config:
              min_replicas: 1
              max_replicas: 4
          engine_kwargs:
            trust_remote_code: true
            tensor_parallel_size: 1
            enable_auto_tool_choice: true
            tool_call_parser: qwen3_coder
            reasoning_parser: qwen3
