// automatically generated by the FlatBuffers compiler, do not modify

package org.ray.spi.impl;

public final class TaskLanguage {
  private TaskLanguage() { }
  public static final int PYTHON = 0;
  public static final int JAVA = 1;

  public static final String[] names = { "PYTHON", "JAVA", };

  public static String name(int e) { return names[e]; }
}

