#!/usr/bin/env bash

echo "-j $(grep -c processor /proc/cpuinfo) --sandbox_fake_username=true --sandbox_fake_hostname=true --sandbox_default_allow_network=false --sandbox_writable_path=/artifact-mount --sandbox_writable_path=/dev/shm --spawn_strategy=linux-sandbox"