group: core tests
depends_on:
  - forge
  - ray-core-build(*)
  - ray-dashboard-build
steps:
  # builds
  - name: corebuild-multipy
    label: "wanda: corebuild-py{{array.python}}"
    wanda: ci/docker/core.build.wanda.yaml
    tags: cibase
    array:
      python:
        - "3.10"
    env:
      PYTHON: "{{array.python}}"
      BASE_TYPE: "build"
      BUILD_VARIANT: "build"
    depends_on: oss-ci-base_build-multipy($)

  - wait: ~
    depends_on:
      - corebuild-multipy(python=3.10)

  # Repro: run gcs_resource_load_puller_test 500x under TSAN with high parallelism
  # to reproduce the data race reported in https://github.com/anyscale/ray/issues/1816
  - label: ":ray: core: TSAN repro gcs_resource_load_puller_test (500x)"
    tags: core_cpp
    instance_type: medium
    commands:
      - RAYCI_DISABLE_TEST_DB=1 bazel run //ci/ray_ci:test_in_docker -- //src/... core
        --bisect-run-test-target //src/ray/gcs/tests:gcs_resource_load_puller_test
        --run-flaky-tests
        --python-version 3.10 --build-name corebuild-py3.10
        --build-type tsan-clang
