
#ifndef RAY_RPC_COMMON_H
#define RAY_RPC_COMMON_H


#include "ray/protobuf/common.pb.h"

namespace ray {
namespace rpc {

template <typename T, typename F>
const std::string GenerateProtobufEnumName(
    T value, F name) {
  return name(value);
}

template <typename T, typename F>
const std::vector<std::string> GenerateProtobufEnumNames(
    T min_value, T max_value, F name) {
  std::vector<std::string> enum_names;

  for (int i = static_cast<int>(min_value);
      i <= static_cast<int>(max_value); i++) {
    
    enum_names.push_back(name(static_cast<T>(i)));
  }
  return enum_names;
}

#define GenerateEnumName(T, value)                                       \
  GenerateProtobufEnumName<T, decltype(BOOST_PP_CAT(T, _Name))>(         \
  value, BOOST_PP_CAT(T, _Name))   \

// For an protobuf enum class T, this function calls 
// `GenerateProtobufEnumNames(T_MIN, T_MAX, T_Name)` to return a vector of enum class names.
// T_MIN, T_MAX, T_Name are auto generated by protobuf compiler (see *.pb.h).
#define GenerateEnumNames(T)                                              \
  GenerateProtobufEnumNames<T, decltype(BOOST_PP_CAT(T, _Name))>(         \
  BOOST_PP_CAT(T, _MIN), BOOST_PP_CAT(T, _MAX), BOOST_PP_CAT(T, _Name))   \

}  // namespace rpc
}  // namespace ray

#endif


