name: "docgpubuild-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_gpu-py$PYTHON"]
dockerfile: ci/docker/docgpu.build.Dockerfile
srcs:
  - python/deplocks/ci/docgpu_gpu_depset_py$PYTHON.lock
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_gpu-py$PYTHON
  - PYTHON
tags:
  - cr.ray.io/rayproject/docgpubuild-py$PYTHON
