ARG DOCKER_IMAGE_BASE
FROM DOCKER_IMAGE_BASE

# Delete stale data
RUN rm -rf /ray

RUN mkdir /ray
WORKDIR /ray

# Below should be re-run each time
COPY . .

# init also calls install-dependencies.sh
RUN bash --login -i NO_DL=1 ./ci/ci.sh init
RUN bash --login -i ./ci/ci.sh build

# Run determine test to run
RUN bash --login -i -c "python ./ci/pipeline/determine_tests_to_run.py --output=json > affected_set.json"
RUN cat affected_set.json
