name: "ray-wheel-py$PYTHON_VERSION$ARCH_SUFFIX"
disable_caching: true
froms:
  - "rayproject/manylinux2014:$MANYLINUX_VERSION$JDK_SUFFIX-$HOSTTYPE"
  - "cr.ray.io/rayproject/ray-core-py$PYTHON_VERSION$ARCH_SUFFIX"     # C++ binaries (ray_pkg.zip)
  - "$RAY_JAVA_IMAGE"                                                 # Java JARs (scratch to skip)
  - "$RAY_DASHBOARD_IMAGE"                                            # Dashboard (scratch to skip)
dockerfile: ci/docker/ray-wheel.Dockerfile
srcs:
  - pyproject.toml
  - README.rst
  - ci/build/build-manylinux-wheel.sh
  - python/
  - rllib/
build_args:
  - PYTHON_VERSION
  - BUILDKITE_COMMIT
  - ARCH_SUFFIX
  - WHEEL_TYPE=ray
  - MANYLINUX_IMAGE=rayproject/manylinux2014:$MANYLINUX_VERSION$JDK_SUFFIX-$HOSTTYPE
  - RAY_CORE_IMAGE=cr.ray.io/rayproject/ray-core-py$PYTHON_VERSION$ARCH_SUFFIX
  - RAY_JAVA_IMAGE
  - RAY_DASHBOARD_IMAGE
artifacts:
  - src: "/opt/artifacts/"
    dst: "./"
