// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/any.proto

package com.google.protobuf;

public interface AnyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Any)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type_url = 1[json_name = "typeUrl"];</code>
   */
  java.lang.String getTypeUrl();
  /**
   * <code>string type_url = 1[json_name = "typeUrl"];</code>
   */
  com.google.protobuf.ByteString
      getTypeUrlBytes();

  /**
   * <code>bytes value = 2[json_name = "value"];</code>
   */
  com.google.protobuf.ByteString getValue();
}
