# Copyright 2025 The Ray Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "zap",
    srcs = [
        "encoder.go",
        "options.go",
        "zap.go",
    ],
    importpath = "github.com/ray-project/ray/go/pkg/log/zap",
    visibility = ["//visibility:public"],
    deps = [
        "//go/pkg/log",
        "//go/pkg/log/lumberjack",
        "@com_github_go_logr_logr//:logr",
        "@com_github_go_logr_zapr//:zapr",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zapcore",
    ],
)

go_test(
    name = "zap_test",
    srcs = ["zap_test.go"],
    embed = [":zap"],
    deps = [
        "//go/pkg/log/lumberjack",
        "@com_github_go_logr_logr//:logr",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zapcore",
        "@org_uber_go_zap//zaptest/observer",
    ],
)
