# --------------------------------------------------------------------
# Tests from the doc/examples directory.
# Please keep these sorted alphabetically, but start with the
# root directory.
# --------------------------------------------------------------------
py_test(
    name = "plot_hyperparameter",
    size = "small",
    srcs = ["examples/plot_hyperparameter.py"],
    tags = []
)

py_test(
    name = "plot_parameter_server",
    size = "small",
    srcs = ["examples/plot_parameter_server.py"],
    tags = []
)

py_test(
    name = "plot_pong_example",
    size = "small",
    srcs = ["examples/plot_pong_example.py"],
    tags = []
)

# Directory: examples/doc_code
py_test(
    name = "doc_code_tf_example",
    size = "small",
    srcs = ["examples/doc_code/tf_example.py"],
    tags = ["tf"]
)

py_test(
    name = "doc_code_torch_example",
    size = "small",
    srcs = ["examples/doc_code/torch_example.py"],
    tags = ["pytorch"]
)
