#!/bin/bash

set -euo pipefail

if [[ "${ANYSCALE_DISABLE_OPTIMIZED_RAY:-}" == "true" || "${ANYSCALE_DISABLE_OPTIMIZED_RAY:-}" == "1" ]]; then
    # User explicitly wants to disable optimized ray, then just exit there.
    exit 0
fi

source /opt/anyscale/version-envs.sh

if [[ "${ANYSCALE_RAY_SITE_PKG_DIR:-}" == "" ]]; then
    echo "ANYSCALE_RAY_SITE_PKG_DIR is not set."
    exit 1
fi

if [[ "${ANYSCALE_PY_VERSION_CODE:-}" == "" ]]; then
    echo "ANYSCALE_PY_VERSION_CODE is not set."
    exit 1
fi

if [[ "${ANYSCALE_RAY_VERSION:-}" == "" ]]; then
    echo "ANYSCALE_RAY_VERSION is not set."
    exit 1
fi

if [[ "${ANYSCALE_RAY_COMMIT:-}" == "" ]]; then
    echo "ANYSCALE_RAY_COMMIT is not set."
    exit 1
fi

readonly SERVICE_SOCK=/tmp/anyscale/anyscaled/sockets/dataplane_service.sock

if [[ ! -S "${SERVICE_SOCK}" ]]; then
    echo "Dataplane service socket not found: ${SERVICE_SOCK}"
    exit 1
fi


rm -rf \
    "${ANYSCALE_RAY_SITE_PKG_DIR}/ray" \
    "${ANYSCALE_RAY_SITE_PKG_DIR}/ray-${ANYSCALE_RAY_VERSION}.dist-info"

if [[ -f /opt/anyscale/ray-opt.tgz ]]; then
    # This is for non-release builds only.
    tar -xzf /opt/anyscale/ray-opt.tgz -C "${ANYSCALE_RAY_SITE_PKG_DIR}"
else
    SITE_PKG_PATH="common/ray-opt/${ANYSCALE_RAY_VERSION}/${ANYSCALE_RAY_COMMIT}/ray-opt-${ANYSCALE_PY_VERSION_CODE}.tar.gz"
    /opt/anyscale/download_anyscale_data "${SITE_PKG_PATH}" | tar -xzf - -C "${ANYSCALE_RAY_SITE_PKG_DIR}"
fi
