load("//java/third_party:workspace.bzl", "maven_dependencies")

maven_dependencies()

git_repository(
    name = "com_github_checkstyle_java",
    commit = "85f37871ca03b9d3fee63c69c8107f167e24e77b",
    remote = "https://github.com/alegithub111/checkstyle_java.git",
)
