# Examples

py_test(
    name = "example_cartpole_mass_maml",
    size = "large",
    srcs = ["examples/cartpole_mass_maml.py"],
    args = ["--run-as-test"],
    main = "cartpole_mass_maml.py",
    tags = [
        "example",
        "team:rllib",
    ],
)

# Learning Tests

# Compilation Tests

py_test(
    name = "test_maml",
    size = "large",
    srcs = ["tests/test_maml.py"],
    tags = [
        "algorithms_dir",
        "team:rllib",
    ],
)
