# Examples

py_test(
    name = "example_cartpole_mass_maml",
    main = "cartpole_mass_maml.py",
    tags = ["team:rllib", "example"],
    size = "large",
    srcs = ["examples/cartpole_mass_maml.py"],
    args = ["--run-as-test"]
)

# Learning Tests


# Compilation Tests

py_test(
    name = "test_maml",
    tags = ["team:rllib", "algorithms_dir"],
    size = "large",
    srcs = ["tests/test_maml.py"]
)
