# Descriptions for caption retrieval

DESCRIPTIONS = [
    "A person cooking in a kitchen",
    "Someone preparing food on a counter",
    "A chef working in a professional kitchen",
    "People eating at a dining table",
    "A group having a meal together",
    "A person working at a desk",
    "Someone typing on a laptop",
    "A business meeting in progress",
    "A presentation being given",
    "People collaborating in an office",
    "A teacher lecturing in a classroom",
    "Students sitting at desks",
    "A person giving a speech",
    "Someone writing on a whiteboard",
    "A customer shopping in a store",
    "People browsing products on shelves",
    "A cashier at a checkout counter",
    "A person exercising at a gym",
    "Someone lifting weights",
    "A person running on a treadmill",
    "People walking on a city sidewalk",
    "Pedestrians crossing a street",
    "Traffic moving through an intersection",
    "Cars driving on a road",
    "A vehicle parked in a lot",
    "People walking through a park",
    "Someone jogging outdoors",
    "A group having a conversation",
    "Two people talking face to face",
    "A person on a phone call",
    "Someone reading a book",
    "A person watching television",
    "People waiting in line",
    "A crowded public space",
    "An empty hallway or corridor",
    "A person entering a building",
    "Someone opening a door",
    "A delivery being made",
    "A person carrying boxes",
    "Workers in a warehouse",
]

