import boto3
import contextlib
import logging
import os
import tempfile
from contextlib import contextmanager
from typing import Any, Dict, Type

import ray.cloudpickle as ray_pickle
from ray.train import Checkpoint
from ray.train._internal.storage import StorageContext
from ray._private.test_utils import simulate_storage
from ray.air._internal.uri_utils import URI


@contextlib.contextmanager
def create_dict_checkpoint(
    data: Dict[str, Any], checkpoint_cls: Type[Checkpoint] = None
) -> Checkpoint:
    with tempfile.TemporaryDirectory() as tmpdir:
        with open(os.path.join(tmpdir, "data.pkl"), "wb") as f:
            ray_pickle.dump(data, f)
        checkpoint_cls = checkpoint_cls or Checkpoint
        yield checkpoint_cls.from_directory(tmpdir)


def load_dict_checkpoint(checkpoint: Checkpoint) -> Dict[str, Any]:
    with checkpoint.as_directory() as checkpoint_dir:
        with open(os.path.join(checkpoint_dir, "data.pkl"), "rb") as f:
            return ray_pickle.load(f)


def mock_storage_context() -> StorageContext:
    storage_path = tempfile.mkdtemp()
    exp_name = "exp_name"
    trial_name = "trial_name"
    storage = StorageContext(
        storage_path=storage_path,
        experiment_dir_name=exp_name,
        trial_dir_name=trial_name,
    )
    storage.storage_local_path = storage_path
    os.makedirs(os.path.join(storage_path, exp_name, trial_name), exist_ok=True)
    return storage


@contextmanager
def mock_s3_bucket_uri():
    port = 5002
    region = "us-west-2"
    with simulate_storage("s3", port=port, region=region) as s3_uri:
        s3 = boto3.client(
            "s3", region_name=region, endpoint_url=f"http://localhost:{port}"
        )
        # Bucket name will be autogenerated/unique per test
        bucket_name = URI(s3_uri).name
        s3.create_bucket(
            Bucket=bucket_name,
            CreateBucketConfiguration={"LocationConstraint": region},
        )
        # Disable server HTTP request logging
        logging.getLogger("werkzeug").setLevel(logging.WARNING)
        yield URI(s3_uri)
        logging.getLogger("werkzeug").setLevel(logging.INFO)
