build_arg_sets:
  py310:
    PYTHON_VERSION: "3.10"
    PYTHON_SHORT: "310"

depsets:
  - name: data_base_ci_depset_${PYTHON_SHORT}
    operation: expand
    depsets:
      - ray_img_depset_${PYTHON_SHORT}
    requirements:
      - python/requirements/test-requirements.txt
      - python/requirements/ml/dl-cpu-requirements.txt
      - python/requirements/ml/data-requirements.txt
    constraints:
      - /tmp/ray-deps/requirements_compiled_py${PYTHON_VERSION}.txt
    output: python/deplocks/ci/data-base-ci_depset_py${PYTHON_VERSION}.lock
    append_flags:
      - --index https://download.pytorch.org/whl/cpu
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
    build_arg_sets:
      - py310

  - name: relaxed_data_ci_depset_${PYTHON_SHORT}
    operation: relax
    source_depset: data_base_ci_depset_${PYTHON_SHORT}
    packages:
      - pyarrow
      - tensorflow-datasets
      - tensorflow-metadata
    output: python/deplocks/ci/relaxed_data-ci_depset_py${PYTHON_VERSION}.lock
    build_arg_sets:
      - py310

  - name: data_tfxbsl_depset_${PYTHON_SHORT}
    operation: expand
    depsets:
      - relaxed_data_ci_depset_${PYTHON_SHORT}
    requirements:
      - python/requirements/data/tfxbsl.txt
    output: python/deplocks/ci/data-tfxbsl-ci_depset_py${PYTHON_VERSION}.lock
    append_flags:
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
      - --upgrade-package pyarrow
    build_arg_sets:
      - py310
