build_arg_sets:
  py310:
    PYTHON_VERSION: "3.10"
    PYTHON_SHORT: "310"
  py312:
    PYTHON_VERSION: "3.12"
    PYTHON_SHORT: "312"


depsets:
  - name: ci_docgpu_depset_${PYTHON_SHORT}
    operation: expand
    depsets:
      - ray_img_depset_${PYTHON_SHORT}
    requirements:
      - python/requirements/test-requirements.txt
      - python/requirements/ml/core-requirements.txt
      - python/requirements/ml/dl-gpu-requirements.txt
      - python/requirements/ml/train-requirements.txt
      - python/requirements/ml/train-test-requirements.txt
      - python/requirements/ml/tune-requirements.txt
      - python/requirements/ml/tune-test-requirements.txt
      - python/requirements/ml/data-requirements.txt
      - python/requirements/ml/rllib-requirements.txt
      - python/requirements/ml/rllib-test-requirements.txt
    output: python/deplocks/ci/docgpu_depset_py${PYTHON_VERSION}.lock
    constraints:
      - /tmp/ray-deps/requirements_compiled_py${PYTHON_VERSION}.txt
    append_flags:
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
      - --unsafe-package pip
    build_arg_sets:
      - py310
      - py312
