build_arg_sets:
  py310:
    PYTHON_VERSION: "3.10"
    PYTHON_SHORT: "310"


depsets:
  - name: docbuild_depset_${PYTHON_SHORT}
    operation: compile
    depsets:
      - ray_img_depset_${PYTHON_SHORT}
    requirements:
      - doc/requirements-doc.txt
    output: python/deplocks/docs/docbuild_depset_py${PYTHON_VERSION}.lock
    append_flags:
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
    build_arg_sets:
      - py310
    include_setuptools: true

  - name: doctest_depset_${PYTHON_SHORT}
    operation: expand
    depsets:
      - ray_img_depset_${PYTHON_SHORT}
    requirements:
      - python/requirements/doc/doc-test-requirements.txt
      - python/requirements/test-requirements.txt
      - python/requirements/ml/train-requirements.txt
      - python/requirements/ml/train-test-requirements.txt
      - python/requirements/ml/tune-requirements.txt
      - python/requirements/ml/tune-test-requirements.txt
      - python/requirements/ml/data-requirements.txt
      - python/requirements/ml/core-requirements.txt
      - python/requirements/ml/rllib-requirements.txt
      - python/requirements/ml/rllib-test-requirements.txt
      - python/requirements/ml/dl-cpu-requirements.txt
    constraints:
      - /tmp/ray-deps/requirements_compiled_py${PYTHON_VERSION}.txt
    output: python/deplocks/docs/doctest_depset_py${PYTHON_VERSION}.lock
    append_flags:
      - --index https://download.pytorch.org/whl/cpu
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
    build_arg_sets:
      - py310
