build_arg_sets:
  py313_cuda130:
    PYTHON_VERSION: "3.13"
    PYTHON_SHORT: "313"
    CUDA_CODE: cu130
  py313_cuda128:
    PYTHON_VERSION: "3.13"
    PYTHON_SHORT: "313"
    CUDA_CODE: cu128
  py313_cpu:
    PYTHON_VERSION: "3.13"
    PYTHON_SHORT: "313"
    CUDA_CODE: cpu

depsets:
  - name: ray_torch_${CUDA_CODE}_base_depset_${PYTHON_SHORT}
    operation: expand
    depsets:
      - ray_img_depset_${PYTHON_SHORT}
    requirements:
      - docker/ray-torch/torch-requirements.txt
      - docker/base-deps/requirements.in
      - docker/base-extra/requirements.in
    constraint: python/deplocks/ray_torch/relaxed_requirements_compiled_py${PYTHON_VERSION}.lock
    output: python/deplocks/ray-torch/ray-torch-${CUDA_CODE}_base_py${PYTHON_VERSION}.lock
    append_flags:
      - --index https://download.pytorch.org/whl/${CUDA_CODE}
      - --unsafe-package ray
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
    build_arg_sets:
      - py313_cuda130
      - py313_cuda128
      - py313_cpu
