{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Profiling a Ray Train Workload with PyTorch Profiler\n",
    "\n",
    "**Time to complete**: 15 min\n",
    "\n",
    "This template profiles PyTorch training code with PyTorch Profiler to identify performance bottlenecks, optimize memory usage, and monitor training efficiency in distributed environments.\n",
    "\n",
    "In this tutorial, you will:\n",
    "1. Start with a basic single machine PyTorch example and learn profiling fundamentals.\n",
    "2. Distribute it to multiple GPUs on multiple machines with [Ray Train](https://docs.ray.io/en/latest/train/train.html) and profile the distributed training workload.\n",
    "3. Explore advanced profiling techniques including memory profiling, performance analysis, and dashboard integration for comprehensive monitoring. \n",
    "\n",
    "\n",
    "With Ray Train, you can profile distributed training workloads across multiple workers, enabling you to identify communication bottlenecks, load balancing issues, and resource utilization patterns that are critical for optimizing large-scale training jobs."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div id=\"anyscale-note\" class=\"alert alert-block alert-warning\">\n",
    "\n",
    "  <strong>Anyscale specific configuration</strong>\n",
    "\n",
    "  <p><strong>Note:</strong> This tutorial is optimized for the Anyscale platform. When running on open source Ray, additional configuration is required. For example, you need to manually:</p>\n",
    "\n",
    "  <ul>\n",
    "    <li><strong>Configure your Ray cluster</strong>: Set up your multi-node environment and manage resource allocation without Anyscale's automation.</li>\n",
    "    <li><strong>Manage dependencies</strong>: Manually install and manage dependencies on each node.</li>\n",
    "    <li><strong>Set up storage</strong>: Configure your own distributed or shared storage system for model checkpointing.</li>\n",
    "  </ul>\n",
    "</div>\n",
    "\n",
    "<style>\n",
    "  div#anyscale-note > p,\n",
    "  div#anyscale-note > ul,\n",
    "  div#anyscale-note > ul li {\n",
    "    color: black;\n",
    "  }\n",
    "\n",
    "  div#anyscale-note {\n",
    "    background-color: rgb(255, 243, 205);\n",
    "  }\n",
    "\n",
    "  div#anyscale-note {\n",
    "    border: 1px solid #ccc; \n",
    "    border-radius: 8px;\n",
    "    padding: 15px;\n",
    "  }\n",
    "\n",
    "</style>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%bash\n",
    "pip install torch torchvision matplotlib"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Distributed training with Ray Train and PyTorch Profiler\n",
    "\n",
    "This example demonstrates how to run PyTorch training with Ray Train with PyTorch profiler. This section uses a simple ResNet model to demonstrate how to use Pytorch Profiler and Ray Train together to analyze model performance.\n",
    "\n",
    "With Ray Train, you can profile distributed training workloads across multiple workers, enabling you to identify communication bottlenecks, load balancing issues, and resource utilization patterns that are critical for optimizing large-scale training jobs.\n",
    "\n",
    "First, set some environment variables and import Ray Train modules.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Enable Ray Train V2 for the latest train API.\n",
    "# V2 will be the default in an upcoming release.\n",
    "import os\n",
    "os.environ[\"RAY_TRAIN_V2_ENABLED\"] = \"1\"\n",
    "\n",
    "# Ray Train imports\n",
    "import ray.train\n",
    "import ray.train.torch\n",
    "from ray.train import RunConfig, ScalingConfig\n",
    "from ray.train.torch import TorchTrainer\n",
    "\n",
    "# PyTorch imports\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import DataLoader\n",
    "from torchvision.datasets import FashionMNIST\n",
    "from torchvision.models import resnet18\n",
    "from torch.optim import Adam\n",
    "from torch.nn import CrossEntropyLoss\n",
    "from torchvision.transforms import Compose, ToTensor, Normalize\n",
    "\n",
    "# Utility imports\n",
    "import tempfile\n",
    "import uuid"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    " Next, create a distributed training function for Ray Train to launch. Each numbered comment in the below training function indicates the steps necessary for distributed training and profiling with Ray Train and Pytorch Profiler.\n",
    "\n",
    "\n",
    " This tutorial uses cluster storage to allow for quick iteration and development, but this may not be suitable in production environments or at high scale. In those cases, you should use object storage instead. For more information about how to select your storage type, see the [Anyscale storage configuration docs](https://docs.anyscale.com/configuration/storage). The output of the script is available in the `Files` tab in Anyscale workspace. For those who don't use Anyscale platform, you can view the logs and profiling output from the configuration location specified in `RunConfig` and `Profiler`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Configure storage path for profiling outputs and training results.\n",
    "# This path serves two purposes:\n",
    "# 1. Ray Train RunConfig uses it as the base location for experiment artifacts,\n",
    "#    checkpoints, and logs (set via RunConfig's storage_path parameter).\n",
    "# 2. PyTorch Profiler writes TensorBoard traces and memory profiles here\n",
    "#    (used in tensorboard_trace_handler and export_memory_timeline calls).\n",
    "# All profiling results and training artifacts will be stored under this path.\n",
    "storage_path = \"/mnt/cluster_storage/\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_func_distributed():\n",
    "    \"\"\"Distributed training function with enhanced profiling for Ray Train.\"\"\"\n",
    "    \n",
    "    # Model, loss, optimizer\n",
    "    model = resnet18(num_classes=10)\n",
    "    model.conv1 = torch.nn.Conv2d(\n",
    "        1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False\n",
    "    )\n",
    "    \n",
    "    # [1] Prepare model for distributed training.\n",
    "    # The prepare_model method wraps the model with DistributedDataParallel\n",
    "    # and moves it to the correct GPU device.\n",
    "    # ================================================================\n",
    "    model = ray.train.torch.prepare_model(model)\n",
    "    \n",
    "    criterion = CrossEntropyLoss()\n",
    "    optimizer = Adam(model.parameters(), lr=0.001)\n",
    "\n",
    "    # Data\n",
    "    transform = Compose([ToTensor(), Normalize((0.28604,), (0.32025,))])\n",
    "    data_dir = os.path.join(tempfile.gettempdir(), \"data\")\n",
    "    train_data = FashionMNIST(root=data_dir, train=True, download=True, transform=transform)\n",
    "    train_loader = DataLoader(train_data, batch_size=128, shuffle=True)\n",
    "    \n",
    "    # [2] Prepare dataloader for distributed training.\n",
    "    # The prepare_data_loader method assigns unique rows of data to each worker\n",
    "    # and handles distributed sampling.\n",
    "    # ========================================================================\n",
    "    train_loader = ray.train.torch.prepare_data_loader(train_loader)\n",
    "\n",
    "    world_rank = ray.train.get_context().get_world_rank()\n",
    "    world_size = ray.train.get_context().get_world_size()\n",
    "\n",
    "    # [3] Configure enhanced profiling for distributed training.\n",
    "    # This includes TensorBoard integration and memory timeline export\n",
    "    # for comprehensive performance analysis across workers.\n",
    "    # See more details at https://docs.pytorch.org/docs/stable/profiler.html\n",
    "    # =============================================================\n",
    "    activities = [torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA]\n",
    "\n",
    "    with torch.profiler.profile(\n",
    "        activities=activities,\n",
    "        schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=1),\n",
    "        on_trace_ready=torch.profiler.tensorboard_trace_handler(f'{storage_path}/logs/distributed'),\n",
    "        record_shapes=True,\n",
    "        profile_memory=True,\n",
    "        with_stack=True,\n",
    "    ) as prof:\n",
    "\n",
    "        # Training loop\n",
    "        for epoch in range(10):\n",
    "            # [4] Set epoch for distributed sampler to ensure proper shuffling\n",
    "            # across all workers in each epoch.\n",
    "            # ==============================================================\n",
    "            if world_size > 1:\n",
    "                train_loader.sampler.set_epoch(epoch)\n",
    "\n",
    "            for batch_idx, (images, labels) in enumerate(train_loader):\n",
    "                outputs = model(images)\n",
    "                loss = criterion(outputs, labels)\n",
    "                optimizer.zero_grad()\n",
    "                loss.backward()\n",
    "                optimizer.step()\n",
    "                prof.step()\n",
    "\n",
    "                # Log performance metrics every 50 batches\n",
    "                if batch_idx % 50 == 0 and world_rank == 0:\n",
    "                    print(f\"Epoch {epoch}, Batch {batch_idx}, Loss: {loss.item():.4f}\")\n",
    "\n",
    "            # [5] Report metrics and checkpoint.\n",
    "            # Each worker reports its metrics and saves checkpoints to shared storage.\n",
    "            # ====================================================================\n",
    "            metrics = {\"loss\": loss.item(), \"epoch\": epoch}\n",
    "            with tempfile.TemporaryDirectory() as temp_checkpoint_dir:\n",
    "                torch.save(\n",
    "                    model.state_dict(),\n",
    "                    os.path.join(temp_checkpoint_dir, \"model.pt\")\n",
    "                )\n",
    "                ray.train.report(\n",
    "                    metrics,\n",
    "                    checkpoint=ray.train.Checkpoint.from_directory(temp_checkpoint_dir),\n",
    "                )\n",
    "            \n",
    "            # Log metrics from rank 0 only to avoid duplicate outputs\n",
    "            if world_rank == 0:\n",
    "                print(f\"Epoch {epoch}, Loss: {loss.item():.4f}\")\n",
    "\n",
    "    # [6] Export memory timeline for each worker.\n",
    "    # This creates separate memory profiles for each worker to analyze\n",
    "    # memory usage patterns across the distributed training job.\n",
    "    # ==============================================================\n",
    "    run_name = ray.train.get_context().get_experiment_name()\n",
    "    prof.export_memory_timeline(\n",
    "        f\"{storage_path}/{run_name}/rank{world_rank}_memory_profile.html\"\n",
    "    )\n",
    "    \n",
    "    if world_rank == 0:\n",
    "        print(f\"Distributed profiling complete! Check '/mnt/cluster_storage/{run_name}/' for worker-specific memory profiles.\")\n",
    "        print(\"Files generated:\")\n",
    "        print(f\"  - rank{world_rank}_memory_profile.html (Memory analysis)\")\n",
    "        print(f\"  - rank{world_rank}_chrome_trace.json (Chrome trace)\")\n",
    "        print(\"  - TensorBoard logs in /mnt/cluster_storage/logs/distributed/\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Finally, run the distributed training function with Ray Train. The `TorchTrainer` orchestrates the distributed training job across multiple workers, each running the profiling-enabled training function.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Configure scaling and resource requirements for distributed training\n",
    "scaling_config = ray.train.ScalingConfig(num_workers=2, use_gpu=True)\n",
    "\n",
    "# Create a unique experiment name for this profiling run\n",
    "experiment_name = f\"profiling_run_{uuid.uuid4().hex[:8]}\"\n",
    "\n",
    "# Configure run settings with persistent storage for profiling outputs.\n",
    "# The storage_path parameter tells Ray Train where to store experiment artifacts,\n",
    "# checkpoints, and logs. This is also the same path where PyTorch Profiler outputs\n",
    "# (TensorBoard traces and memory profiles) are written to, allowing you to access\n",
    "# all training and profiling results from a single location.\n",
    "run_config = ray.train.RunConfig(\n",
    "    storage_path=storage_path,\n",
    "    name=experiment_name,\n",
    ")\n",
    "\n",
    "# Launch distributed training job with profiling\n",
    "trainer = ray.train.torch.TorchTrainer(\n",
    "    train_func_distributed,\n",
    "    scaling_config=scaling_config,\n",
    "    run_config=run_config,\n",
    ")\n",
    "\n",
    "print(f\"Starting distributed training with profiling: {experiment_name}\")\n",
    "result = trainer.fit()\n",
    "print(f\"Distributed training with profiling completed successfully! Results are: {result}\")\n",
    "print(f\"Check '{storage_path}/{experiment_name}/' for profiling results.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Advanced profiling techniques and dashboard integration\n",
    "\n",
    "This section explores advanced profiling techniques including custom profiling schedules, performance analysis, and integration with Ray Train's monitoring capabilities. These techniques help you gain deeper insights into your training workload performance and identify optimization opportunities.\n",
    "\n",
    "### Custom profiling schedules and performance analysis\n",
    "\n",
    "PyTorch Profiler offers flexible scheduling options to capture different phases of training. You can configure when profiling occurs to focus on specific operations or phases of your training loop.\n",
    "\n",
    "The following code section adapts the previous training function with `torch.profile.record_function` to record some specific operations.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_func_advanced_profiling():\n",
    "    \"\"\"Advanced profiling example with custom schedules and performance analysis.\"\"\"\n",
    "    \n",
    "    # Model setup\n",
    "    model = resnet18(num_classes=10)\n",
    "    model.conv1 = torch.nn.Conv2d(\n",
    "        1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False\n",
    "    )\n",
    "    model = ray.train.torch.prepare_model(model)\n",
    "    \n",
    "    criterion = CrossEntropyLoss()\n",
    "    optimizer = Adam(model.parameters(), lr=0.001)\n",
    "\n",
    "    # Data setup\n",
    "    transform = Compose([ToTensor(), Normalize((0.28604,), (0.32025,))])\n",
    "    data_dir = os.path.join(tempfile.gettempdir(), \"data\")\n",
    "    train_data = FashionMNIST(root=data_dir, train=True, download=True, transform=transform)\n",
    "    train_loader = DataLoader(train_data, batch_size=128, shuffle=True)\n",
    "    train_loader = ray.train.torch.prepare_data_loader(train_loader)\n",
    "\n",
    "    world_rank = ray.train.get_context().get_world_rank()\n",
    "    \n",
    "    # [1] Advanced profiling configuration with custom schedule.\n",
    "    # This schedule profiles every 2nd step to reduce overhead while\n",
    "    # still capturing representative performance data.\n",
    "    # ==============================================================\n",
    "    activities = [torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA]\n",
    "    \n",
    "    # Custom schedule: wait=1, warmup=1, active=3, repeat=1\n",
    "    # This means the profiler skips 1 step, then warmups for 1 step, then does the active profiling for 3 steps, then repeats.\n",
    "    # See more details at https://docs.pytorch.org/docs/stable/profiler.html#torch.profiler.schedule\n",
    "    schedule = torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=1)\n",
    "    \n",
    "    with torch.profiler.profile(\n",
    "        activities=activities,\n",
    "        schedule=schedule,\n",
    "        on_trace_ready=torch.profiler.tensorboard_trace_handler(f'{storage_path}/logs/advanced'),\n",
    "        record_shapes=True,\n",
    "        profile_memory=True,\n",
    "        with_stack=True,\n",
    "        # [2] Enable experimental Kineto library features for enhanced analysis.\n",
    "        # Kineto is a library that provides performance observability and diagnostic to deprecate TensorBoard.\n",
    "        # See more details at https://github.com/pytorch/kineto.\n",
    "        # ======================================================\n",
    "        experimental_config=torch.profiler._ExperimentalConfig(verbose=True),\n",
    "    ) as prof:\n",
    "\n",
    "        # Training loop with performance monitoring\n",
    "        for epoch in range(10):\n",
    "            if ray.train.get_context().get_world_size() > 1:\n",
    "                train_loader.sampler.set_epoch(epoch)\n",
    "\n",
    "            epoch_start_time = torch.cuda.Event(enable_timing=True)\n",
    "            epoch_end_time = torch.cuda.Event(enable_timing=True)\n",
    "            \n",
    "            epoch_start_time.record()\n",
    "            \n",
    "            for batch_idx, (images, labels) in enumerate(train_loader):\n",
    "                # [3] Profile individual operations for detailed analysis.\n",
    "                # ========================================================\n",
    "                with torch.profiler.record_function(\"forward_pass\"):\n",
    "                    outputs = model(images)\n",
    "                \n",
    "                with torch.profiler.record_function(\"loss_computation\"):\n",
    "                    loss = criterion(outputs, labels)\n",
    "                \n",
    "                with torch.profiler.record_function(\"backward_pass\"):\n",
    "                    optimizer.zero_grad()\n",
    "                    loss.backward()\n",
    "                    optimizer.step()\n",
    "                \n",
    "                prof.step()\n",
    "                \n",
    "                # Log performance metrics every 50 batches\n",
    "                if batch_idx % 50 == 0 and world_rank == 0:\n",
    "                    print(f\"Epoch {epoch}, Batch {batch_idx}, Loss: {loss.item():.4f}\")\n",
    "\n",
    "            epoch_end_time.record()\n",
    "            # Wait for GPU operations to complete since CUDA operations are asynchronous.\n",
    "            torch.cuda.synchronize()\n",
    "            \n",
    "            # [4] Calculate and report timing metrics.\n",
    "            # ======================================\n",
    "            epoch_time = epoch_start_time.elapsed_time(epoch_end_time)\n",
    "            metrics = {\n",
    "                \"loss\": loss.item(), \n",
    "                \"epoch\": epoch,\n",
    "                \"epoch_time_ms\": epoch_time,\n",
    "                \"profiler_step\": prof.step_num\n",
    "            }\n",
    "            \n",
    "            with tempfile.TemporaryDirectory() as temp_checkpoint_dir:\n",
    "                torch.save(\n",
    "                    model.state_dict(),\n",
    "                    os.path.join(temp_checkpoint_dir, \"model.pt\")\n",
    "                )\n",
    "                ray.train.report(\n",
    "                    metrics,\n",
    "                    checkpoint=ray.train.Checkpoint.from_directory(temp_checkpoint_dir),\n",
    "                )\n",
    "            \n",
    "            if world_rank == 0:\n",
    "                print(f\"Epoch {epoch} completed in {epoch_time:.2f}ms\")\n",
    "\n",
    "    # [5] Export comprehensive profiling data.\n",
    "    # ======================================\n",
    "    run_name = ray.train.get_context().get_experiment_name()\n",
    "    \n",
    "    # Export memory timeline\n",
    "    prof.export_memory_timeline(\n",
    "        f\"{storage_path}/{run_name}/rank{world_rank}_advanced_memory_profile.html\"\n",
    "    )\n",
    "    \n",
    "    \n",
    "    if world_rank == 0:\n",
    "        print(f\"Advanced profiling complete! Check '{storage_path}/{run_name}/' for detailed profiling results.\")\n",
    "        print(\"Files generated:\")\n",
    "        print(f\"  - rank{world_rank}_advanced_memory_profile.html (Memory analysis)\")\n",
    "        print(f\"  - rank{world_rank}_chrome_trace.json (Chrome trace)\")\n",
    "        print(f\"  - TensorBoard logs in '{storage_path}/logs/advanced/'\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Kick off the Ray Train job similarly to the previous step."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run the advanced profiling example\n",
    "scaling_config = ray.train.ScalingConfig(num_workers=2, use_gpu=True)\n",
    "\n",
    "# Create a unique experiment name for advanced profiling\n",
    "advanced_experiment_name = f\"advanced_profiling_{uuid.uuid4().hex[:8]}\"\n",
    "\n",
    "# Configure run settings with storage_path for both Ray Train artifacts and profiler output\n",
    "run_config = ray.train.RunConfig(\n",
    "    storage_path=storage_path,\n",
    "    name=advanced_experiment_name,\n",
    ")\n",
    "\n",
    "# Launch advanced profiling training job\n",
    "trainer = ray.train.torch.TorchTrainer(\n",
    "    train_func_advanced_profiling,\n",
    "    scaling_config=scaling_config,\n",
    "    run_config=run_config,\n",
    ")\n",
    "\n",
    "print(f\"Starting advanced profiling training: {advanced_experiment_name}\")\n",
    "result = trainer.fit()\n",
    "print(f\"Advanced profiling training completed successfully! Results are: {result}\")\n",
    "print(f\"Check '{storage_path}/{advanced_experiment_name}/' for comprehensive profiling results.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Analyzing profiling results\n",
    "\n",
    "After running the profiling examples, you have access to several types of profiling data:\n",
    "\n",
    "1. **TensorBoard traces**: Located in `/mnt/cluster_storage/logs/` or the persistent storage that you configured. Use these traces to visualize GPU/CPU utilization, kernel execution times, and memory allocation patterns.\n",
    "\n",
    "2. **Memory timeline HTML files**: Worker-specific memory profiles showing memory usage over time, helping identify memory leaks and optimization opportunities.\n",
    "\n",
    "\n",
    "3. **Ray Train dashboard**: If using Anyscale workspace, access the Ray Train dashboard to monitor real-time metrics, worker status, and resource utilization.\n",
    "\n",
    "### Key profiling insights to look for:\n",
    "\n",
    "- **GPU utilization**: Ensure your workload is using GPUs efficiently (high utilization percentage)\n",
    "- **Memory usage patterns**: Look for memory spikes, leaks, or inefficient allocation patterns\n",
    "- **Communication overhead**: Monitor time spent on gradient synchronization\n",
    "- **Data loading bottlenecks**: Identify if data loading is limiting training throughput\n",
    "- **Kernel efficiency**: Analyze which operations are taking the most time and optimize accordingly\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tensorboard plugin with PyTorch Profiler and tracing.\n",
    "\n",
    "After generating the `trace.json` files, you can use Tensorboard, or drag the `trace.json` into Perfetto UI or `chrome://tracing` to visualize your profile."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Use the script below to start the Tensorboard.\n",
    "```\n",
    "pip install torch_tb_profiler\n",
    "\n",
    "# Once you run the above code, the profiling result is saved under `/mnt/cluster_storage/logs/`\n",
    "tensorboard --logdir=/mnt/cluster_storage/logs/\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Open the TensorBoard profile URL in a browser and you can see the Profiler plugin page as shown below."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "<div style=\"display: flex; gap: 40px; align-items: flex-start;\">\n",
    "  <div style=\"text-align: center;\">\n",
    "    <img src=\"https://raw.githubusercontent.com/ray-project/ray/master/doc/source/train/examples/pytorch/pytorch-profiling/images/tensorboard_overview.png\" width=\"600\"/>\n",
    "  </div>\n",
    "</div>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The following page shows worker-specific memory profiles showing memory usage over time, helping identify memory leaks and optimization opportunities.\n",
    "\n",
    "<div style=\"display: flex; gap: 40px; align-items: flex-start;\">\n",
    "  <div style=\"text-align: center;\">\n",
    "    <img src=\"https://raw.githubusercontent.com/ray-project/ray/master/doc/source/train/examples/pytorch/pytorch-profiling/images/memory_html.png\" width=\"600\"/>\n",
    "  </div>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The advanced section uses `record_function` context to profile individual operations, which you can view in the trace section:\n",
    "<div style=\"display: flex; gap: 40px; align-items: flex-start;\">\n",
    "  <div style=\"text-align: center;\">\n",
    "    <img src=\"https://raw.githubusercontent.com/ray-project/ray/master/doc/source/train/examples/pytorch/pytorch-profiling/images/trace_annotation.png\" width=\"600\"/>\n",
    "  </div>\n",
    "</div>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Summary\n",
    "\n",
    "In this notebook, you learned how to profile Ray Train workloads using PyTorch Profiler:\n",
    "\n",
    "- **Single machine profiling**: Started with basic profiling fundamentals, learning how to integrate PyTorch Profiler into your training loop to monitor performance and identify bottlenecks.\n",
    "\n",
    "- **Distributed profiling**: Scaled to multi-worker distributed training with Ray Train, enabling profiling across multiple GPUs and machines to identify communication overhead and load balancing issues.\n",
    "\n",
    "- **Advanced profiling techniques**: Explored custom profiling schedules, operation-level profiling, and comprehensive data export including TensorBoard traces, memory timelines, and Chrome traces.\n",
    "\n",
    "- **Performance optimization**: Gained insights into GPU utilization, memory usage patterns, and training efficiency through detailed profiling analysis.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orphan": true
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
