# Examples

py_test(
    name = "example_bandit_linucb_interest_evolution_recsim",
    size = "large",
    srcs = ["examples/bandit_linucb_interest_evolution_recsim.py"],
    args = ["--run-as-test"],
    main = "bandit_linucb_interest_evolution_recsim.py",
    tags = [
        "example",
        "team:rllib",
    ],
)

py_test(
    name = "examples/lin_ts_train_wheel_env",
    size = "small",
    srcs = ["examples/lin_ts_train_wheel_env.py"],
    main = "examples/lin_ts_train_wheel_env.py",
    tags = [
        "examples",
        "team:rllib",
    ],
)

py_test(
    name = "examples/tune_lin_ts_train_wheel_env",
    size = "small",
    srcs = ["examples/tune_lin_ts_train_wheel_env.py"],
    main = "examples/tune_lin_ts_train_wheel_env.py",
    tags = [
        "examples",
        "team:rllib",
    ],
)

py_test(
    name = "examples/tune_lin_ucb_train_recommendation",
    size = "small",
    srcs = ["examples/tune_lin_ucb_train_recommendation.py"],
    main = "examples/tune_lin_ucb_train_recommendation.py",
    tags = [
        "examples",
        "team:rllib",
    ],
)

py_test(
    name = "examples/tune_lin_ucb_train_recsim_env",
    size = "small",
    srcs = ["examples/tune_lin_ucb_train_recsim_env.py"],
    main = "examples/tune_lin_ucb_train_recsim_env.py",
    tags = [
        "examples",
        "team:rllib",
    ],
)

# Learning Tests

# Compilation Tests

py_test(
    name = "test_bandit",
    size = "large",
    srcs = ["tests/test_bandit.py"],
    tags = [
        "algorithms_dir",
        "team:rllib",
    ],
)
