# Examples

py_test(
    name = "example_bandit_linucb_interest_evolution_recsim",
    main = "bandit_linucb_interest_evolution_recsim.py",
    tags = ["team:rllib", "example"],
    size = "large",
    srcs = ["examples/bandit_linucb_interest_evolution_recsim.py"],
    args = ["--run-as-test"]
)

py_test(
    name = "examples/lin_ts_train_wheel_env",
    main = "examples/lin_ts_train_wheel_env.py",
    tags = ["team:rllib", "examples"],
    size = "small",
    srcs = ["examples/lin_ts_train_wheel_env.py"],
)

py_test(
    name = "examples/tune_lin_ts_train_wheel_env",
    main = "examples/tune_lin_ts_train_wheel_env.py",
    tags = ["team:rllib", "examples"],
    size = "small",
    srcs = ["examples/tune_lin_ts_train_wheel_env.py"],
)

py_test(
    name = "examples/tune_lin_ucb_train_recommendation",
    main = "examples/tune_lin_ucb_train_recommendation.py",
    tags = ["team:rllib",  "examples"],
    size = "small",
    srcs = ["examples/tune_lin_ucb_train_recommendation.py"],
)

py_test(
    name = "examples/tune_lin_ucb_train_recsim_env",
    main = "examples/tune_lin_ucb_train_recsim_env.py",
    tags = ["team:rllib", "examples"],
    size = "small",
    srcs = ["examples/tune_lin_ucb_train_recsim_env.py"],
)

# Learning Tests


# Compilation Tests

py_test(
    name = "test_bandit",
    tags = ["team:rllib", "algorithms_dir"],
    size = "large",
    srcs = ["tests/test_bandit.py"]
)
