# Examples

py_test(
    name = "example_bandit_linucb_interest_evolution_recsim",
    main = "bandit_linucb_interest_evolution_recsim.py",
    tags = ["team:rllib", "example"],
    size = "large",
    srcs = ["examples/bandit_linucb_interest_evolution_recsim.py"],
    args = ["--run-as-test"]
)

# Learning Tests


# Compilation Tests

py_test(
    name = "test_bandit",
    tags = ["team:rllib", "algorithms_dir"],
    size = "large",
    srcs = ["tests/test_bandit.py"]
)
