py_test(
    name = "test_controller",
    size = "small",
    srcs = ["tests/test_controller.py"],
    tags = ["exclusive", "team:ml", "train_v2"],
    deps = ["//:ray_lib"],
)

py_test(
    name = "test_data_parallel_trainer",
    size = "small",
    srcs = ["tests/test_data_parallel_trainer.py"],
    tags = ["exclusive", "team:ml", "train_v2"],
    deps = ["//:ray_lib"],
)

py_test(
    name = "test_failure_policy",
    size = "small",
    srcs = ["tests/test_failure_policy.py"],
    tags = ["exclusive", "team:ml", "train_v2"],
    deps = ["//:ray_lib"],
)

py_test(
    name = "test_worker_group_v2",
    size = "small",
    srcs = ["tests/test_worker_group_v2.py"],
    tags = ["exclusive", "team:ml", "train_v2"],
    deps = ["//:ray_lib"],
)
