load("//bazel:ray.bzl", "ray_cc_library")

ray_cc_library(
    name = "postable",
    hdrs = [
        "postable.h",
    ],
    visibility = [
        ":__subpackages__",
        "//src/ray/gcs:__pkg__",
        "//src/ray/gcs/store_client:__pkg__",
    ],
    deps = [
        ":function_traits",
        "//src/ray/asio:instrumented_io_context",
    ],
)

ray_cc_library(
    name = "function_traits",
    hdrs = ["function_traits.h"],
    visibility = [":__subpackages__"],
    deps = [
        "@boost//:functional",
    ],
)
