// Copyright 2017 The Ray Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_ray_runtime_metric_NativeMetric */

#ifndef _Included_io_ray_runtime_metric_NativeMetric
#define _Included_io_ray_runtime_metric_NativeMetric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_ray_runtime_metric_NativeMetric
 * Method:    registerTagkeyNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_io_ray_runtime_metric_NativeMetric_registerTagkeyNative(JNIEnv *, jclass, jstring);

/*
 * Class:     io_ray_runtime_metric_NativeMetric
 * Method:    registerCountNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_io_ray_runtime_metric_NativeMetric_registerCountNative(
    JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     io_ray_runtime_metric_NativeMetric
 * Method:    registerGaugeNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_io_ray_runtime_metric_NativeMetric_registerGaugeNative(
    JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     io_ray_runtime_metric_NativeMetric
 * Method:    registerHistogramNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[DLjava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_io_ray_runtime_metric_NativeMetric_registerHistogramNative(
    JNIEnv *, jclass, jstring, jstring, jstring, jdoubleArray, jobject);

/*
 * Class:     io_ray_runtime_metric_NativeMetric
 * Method:    registerSumNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_io_ray_runtime_metric_NativeMetric_registerSumNative(
    JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     io_ray_runtime_metric_NativeMetric
 * Method:    recordNative
 * Signature: (JDLjava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_io_ray_runtime_metric_NativeMetric_recordNative(
    JNIEnv *, jclass, jlong, jdouble, jobject, jobject);

/*
 * Class:     io_ray_runtime_metric_NativeMetric
 * Method:    unregisterMetricNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_io_ray_runtime_metric_NativeMetric_unregisterMetricNative(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
