/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ray_runtime_TaskInterface */

#ifndef _Included_org_ray_runtime_TaskInterface
#define _Included_org_ray_runtime_TaskInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ray_runtime_TaskInterface
 * Method:    submitTask
 * Signature:
 * (JLorg/ray/runtime/nativeTypes/NativeRayFunction;Ljava/util/List;Lorg/ray/runtime/nativeTypes/NativeTaskOptions;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_ray_runtime_TaskInterface_submitTask(JNIEnv *, jclass,
                                                                        jlong, jobject,
                                                                        jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
