/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ray_runtime_TaskInterface */

#ifndef _Included_org_ray_runtime_TaskInterface
#define _Included_org_ray_runtime_TaskInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ray_runtime_TaskInterface
 * Method:    submitTask
 * Signature:
 * (JLorg/ray/runtime/proxyTypes/RayFunctionProxy;Ljava/util/List;Lorg/ray/runtime/proxyTypes/TaskOptionsProxy;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_ray_runtime_TaskInterface_submitTask(JNIEnv *, jclass,
                                                                        jlong, jobject,
                                                                        jobject, jobject);

/*
 * Class:     org_ray_runtime_TaskInterface
 * Method:    createActor
 * Signature:
 * (JLorg/ray/runtime/proxyTypes/RayFunctionProxy;Ljava/util/List;Lorg/ray/runtime/proxyTypes/ActorCreationOptionsProxy;)J
 */
JNIEXPORT jlong JNICALL Java_org_ray_runtime_TaskInterface_createActor(JNIEnv *, jclass,
                                                                       jlong, jobject,
                                                                       jobject, jobject);

/*
 * Class:     org_ray_runtime_TaskInterface
 * Method:    submitActorTask
 * Signature:
 * (JJLorg/ray/runtime/proxyTypes/RayFunctionProxy;Ljava/util/List;Lorg/ray/runtime/proxyTypes/TaskOptionsProxy;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_ray_runtime_TaskInterface_submitActorTask(
    JNIEnv *, jclass, jlong, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
