/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ray_runtime_CoreWorkerProxy */

#ifndef _Included_org_ray_runtime_CoreWorkerProxy
#define _Included_org_ray_runtime_CoreWorkerProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ray_runtime_CoreWorkerProxy
 * Method:    createCoreWorker
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_org_ray_runtime_CoreWorkerProxy_createCoreWorker(
    JNIEnv *, jclass, jstring, jstring, jbyteArray);

/*
 * Class:     org_ray_runtime_CoreWorkerProxy
 * Method:    runCoreWorker
 * Signature: (JLorg/ray/runtime/CoreWorkerProxy;)V
 */
JNIEXPORT void JNICALL Java_org_ray_runtime_CoreWorkerProxy_runCoreWorker(JNIEnv *,
                                                                          jclass, jlong,
                                                                          jobject);

#ifdef __cplusplus
}
#endif
#endif
