# Examples

py_test(
    name = "example_leela_chess_zero_connect_4",
    main = "leela_chess_zero_connect_4.py",
    tags = ["team:rllib", "example"],
    size = "large",
    srcs = ["examples/leela_chess_zero_connect_4.py"],
    args = ["--run-as-test"]
)

# Learning Tests


# Compilation Tests

py_test(
    name = "test_leela_chess_zero",
    tags = ["team:rllib", "algorithms_dir"],
    size = "large",
    srcs = ["tests/test_leela_chess_zero.py"]
)
