py_test(
 name = "simple_example",
 size = "small",
 srcs = ["simple_example.py"],
 deps = ["//:ray_lib"],
 tags = ["team:ml", "compat", "exclusive"],
)

py_test(
 name = "simple_tune",
 size="small",
 srcs = ["simple_tune.py"],
 deps = ["//:ray_lib"],
 tags = ["team:ml", "compat", "exclusive"]
)