py_test(
    name = "test_runtime_env_validation",
    srcs = ["test_runtime_env_validation.py"],
    tags = ["team:core"],
    deps = [
        "//python/ray/_private/runtime_env:validation",
    ],
)

py_test(
    name = "test_uv",
    srcs = ["test_uv.py"],
    tags = ["team:core"],
    deps = [
        "//python/ray/_private/runtime_env:uv",
    ],
)
