py_test(
    name = "runtime_env_validation_unit_test",
    srcs = ["runtime_env_validation_unit_test.py"],
    tags = ["team:core"],
    deps = [
        "//python/ray/_private/runtime_env:validation",
    ],
)
