# --------------------------------------------------------------------
# Tests from the python/ray/tests/ray_lightning directory.
# Please keep these sorted alphabetically.
# --------------------------------------------------------------------
py_test(
 name = "simple_example",
 size = "small",
 srcs = ["simple_example.py"],
 tags = ["team:ml", "exclusive"],
)

py_test(
 name = "simple_tune",
 size="small",
 srcs = ["simple_tune.py"],
 tags = ["team:ml", "exclusive"]
)


