# --------------------------------------------------------------------
# Tests from the python/ray/tests/xgboost directory.
# Please keep these sorted alphabetically.
# --------------------------------------------------------------------
py_test(
 name = "simple_example",
 size = "small",
 srcs = ["simple_example.py"],
 deps = ["//:ray_lib"],
 tags = ["team:ml", "compat", "compat_py36", "exclusive"],
)

py_test(
 name = "simple_tune",
 size="small",
 srcs = ["simple_tune.py"],
 deps = ["//:ray_lib"],
 tags = ["team:ml", "compat", "compat_py36", "exclusive"]
)


