#!/bin/bash
# Run a command, suppressing output unless it hangs or crashes.

TIMEOUT=30m
TMPFILE=`mktemp`
COMMAND="$@"

# Print output to avoid travis killing us
progress() {
    sleep 5m
    echo "This command has been running for more than 5 minutes..."
    while true; do
        sleep 5m
        echo "This command is still running..."
    done
}

progress & 2>/dev/null
prog=$!

if which timeout >/dev/null; then
    timeout -k $TIMEOUT $TIMEOUT $COMMAND >$TMPFILE 2>&1
else
    $COMMAND >$TMPFILE 2>&1
fi

CODE=$?
if [ $CODE != 0 ]; then
    cat $TMPFILE
    echo "FAILED $CODE"
    kill $prog
    exit $CODE
fi

kill $prog
