# Copyright (2023 and onwards) Anyscale, Inc.

import os

ANYSCALE_RAY_SERVE_ENABLE_PROPRIETARY_DEPLOYMENT_SCHEDULER = (
    os.environ.get("ANYSCALE_RAY_SERVE_ENABLE_PROPRIETARY_DEPLOYMENT_SCHEDULER", "1")
    == "1"
)

ANYSCALE_RAY_SERVE_DEFAULT_DRAINING_TIMEOUT_S = float(
    os.environ.get("ANYSCALE_RAY_SERVE_DEFAULT_DRAINING_TIMEOUT_S", 300.0)
)

# Default to 30 minutes
ANYSCALE_RAY_SERVE_COMPACTION_TIMEOUT_S = float(
    os.environ.get("ANYSCALE_RAY_SERVE_COMPACTION_TIMEOUT_S", 1800.0)
)
