{
 "title": "Default Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Ray Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Instance Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ray_cluster_active_nodes", "legendFormat": "Active Nodes ({{node_type}})" },
    { "expr": "ray_cluster_failed_nodes", "legendFormat": "Failed Nodes {{node_type}}" },
    { "expr": "ray_cluster_pending_nodes", "legendFormat": "Pending Nodes ({{node_type}})" }
   ]
  },
  {
   "title": "Ray Node Resource Utilization (Percentage)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ray_node_cpu_utilization{instance=~\"$Instance\"} * ray_node_cpu_count{instance=~\"$Instance\"}) / sum(ray_node_cpu_count{instance=~\"$Instance\"})",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\"}) * 100 / sum(ray_node_mem_total{instance=~\"$Instance\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\"}) * 100 / sum(ray_node_disk_usage{instance=~\"$Instance\"} + ray_node_disk_free{instance=~\"$Instance\"})",
     "legendFormat": "Disk Utilization"
    },
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\"} * 100 / ray_node_gpus_available{instance=~\"$Instance\"}",
     "legendFormat": "GPUs Utilization"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "ray_node_cpu_utilization{instance=~\"$Instance\"} * ray_node_cpu_count{instance=~\"$Instance\"} / 100",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "ray_node_cpu_count{instance=~\"$Instance\"}",
     "legendFormat": "CPU Count: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_mem_used{instance=~\"$Instance\"}",
     "legendFormat": "Memory Used: {{instance}}"
    },
    {
     "expr": "ray_node_mem_available{instance=~\"$Instance\"}",
     "legendFormat": "Memory Available: {{instance}}"
    },
    {
     "expr": "ray_node_mem_total{instance=~\"$Instance\"}",
     "legendFormat": "Memory Total: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"}",
     "legendFormat": "Disk Used: {{instance}}"
    },
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"} / (ray_node_disk_utilization_percentage{instance=~\"$Instance\"} / 100)",
     "legendFormat": "Disk Total: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "ray_node_network_receive_speed{instance=~\"$Instance\"}",
     "legendFormat": "Network Receive: {{instance}}"
    },
    {
     "expr": "ray_node_network_send_speed{instance=~\"$Instance\"}",
     "legendFormat": "Network Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Node GPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\"} OR vector(0)",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "ray_node_gpus_available{instance=~\"$Instance\"} OR vector(0)",
     "legendFormat": "GPU Available: {{instance}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory (GRAM)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Used GRAM: {{instance}}"
    },
    {
     "expr": "ray_node_gram_available{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Available GRAM: {{instance}}"
    },
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\"} + on(NodeAddress) node_gram_available{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Total GRAM: {{instance}}"
    }
   ]
  }
 ]
}