ARG DOCKER_IMAGE_BASE_BUILD
FROM $DOCKER_IMAGE_BASE_BUILD

ENV NO_INSTALL=1
ENV RAY_TEST_SCRIPT=./run_release_test
ENV NO_ARTIFACTS=1

RUN mkdir -p /rayci
WORKDIR /rayci
COPY . .
ENTRYPOINT ["bash", "./run"]
