load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "vm_transfer",
    srcs = ["vm_transfer.cc"],
    hdrs = ["vm_transfer.h"],
    strip_include_prefix = "//src",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "fd_transfer",
    srcs = ["fd_transfer.cc"],
    hdrs = ["fd_transfer.h"],
    strip_include_prefix = "//src",
    visibility = ["//visibility:public"],
)
