/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ray_streaming_runtime_queue_QueueID */

#ifndef _Included_org_ray_streaming_runtime_queue_QueueID
#define _Included_org_ray_streaming_runtime_queue_QueueID
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ray_streaming_runtime_queue_QueueID_ID_LENGTH
#define org_ray_streaming_runtime_queue_QueueID_ID_LENGTH 20L
/*
 * Class:     org_ray_streaming_runtime_queue_QueueID
 * Method:    createNativeID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ray_streaming_runtime_queue_QueueID_createNativeID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ray_streaming_runtime_queue_QueueID
 * Method:    destroyNativeID
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ray_streaming_runtime_queue_QueueID_destroyNativeID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
