# Examples

py_test(
    name = "example_apex_ddpg_pendulum_v1",
    size = "large",
    srcs = ["examples/apex_ddpg_pendulum_v1.py"],
    args = ["--run-as-test"],
    main = "apex_ddpg_pendulum_v1.py",
    tags = [
        "example",
        "team:rllib",
    ],
)

# Learning Tests

# Compilation Tests

py_test(
    name = "test_apex_ddpg",
    size = "large",
    srcs = ["tests/test_apex_ddpg.py"],
    tags = [
        "algorithms_dir",
        "team:rllib",
    ],
)
