# Examples

py_test(
    name = "example_apex_ddpg_pendulum_v1",
    main = "apex_ddpg_pendulum_v1.py",
    tags = ["team:rllib", "example"],
    size = "large",
    srcs = ["examples/apex_ddpg_pendulum_v1.py"],
    args = ["--run-as-test"]
)

# Learning Tests


# Compilation Tests

py_test(
    name = "test_apex_ddpg",
    tags = ["team:rllib", "algorithms_dir"],
    size = "large",
    srcs = ["tests/test_apex_ddpg.py"]
)
