export const timezones = [
  {
    utc: "GMT-12:00",
    value: "Etc/GMT+12",
    group: "Pacific",
    country: "International Date Line West",
  },
  {
    utc: "GMT-11:00",
    value: "Pacific/Pago_Pago",
    group: "Pacific",
    country: "American Samoa",
  },
  {
    utc: "GMT-11:00",
    value: "Pacific/Midway",
    group: "Pacific",
    country: "Midway Island",
  },
  {
    utc: "GMT-10:00",
    value: "Pacific/Honolulu",
    group: "Pacific",
    country: "Hawaii",
  },
  {
    utc: "GMT-09:00",
    value: "America/Anchorage",
    group: "America",
    country: "Alaska",
  },
  {
    utc: "GMT-08:00",
    value: "America/Los_Angeles",
    group: "America",
    country: "Pacific Time (US & Canada)",
  },
  {
    utc: "GMT-08:00",
    value: "America/Tijuana",
    group: "America",
    country: "Tijuana",
  },
  {
    utc: "GMT-07:00",
    value: "America/Phoenix",
    group: "America",
    country: "Arizona",
  },
  {
    utc: "GMT-07:00",
    value: "America/Mazatlan",
    group: "America",
    country: "Mazatlan",
  },
  {
    utc: "GMT-07:00",
    value: "America/Denver",
    group: "America",
    country: "Mountain Time (US & Canada)",
  },
  {
    utc: "GMT-06:00",
    value: "America/Guatemala",
    group: "America",
    country: "Central America",
  },
  {
    utc: "GMT-06:00",
    value: "America/Chicago",
    group: "America",
    country: "Central Time (US & Canada)",
  },
  {
    utc: "GMT-06:00",
    value: "America/Chihuahua",
    group: "America",
    country: "Chihuahua",
  },
  {
    utc: "GMT-06:00",
    value: "America/Guadalajara",
    group: "America",
    country: "Guadalajara",
  },
  {
    utc: "GMT-06:00",
    value: "America/Mexico_City",
    group: "America",
    country: "Mexico City",
  },
  {
    utc: "GMT-06:00",
    value: "America/Monterrey",
    group: "America",
    country: "Monterrey",
  },
  {
    utc: "GMT-06:00",
    value: "America/Regina",
    group: "America",
    country: "Saskatchewan",
  },
  {
    utc: "GMT-05:00",
    value: "America/Bogota",
    group: "America",
    country: "Bogota",
  },
  {
    utc: "GMT-05:00",
    value: "America/New_York",
    group: "America",
    country: "Eastern Time (US & Canada)",
  },
  {
    utc: "GMT-05:00",
    value: "America/Indiana/Indianapolis",
    group: "America",
    country: "Indiana (East)",
  },
  {
    utc: "GMT-05:00",
    value: "America/Lima",
    group: "America",
    country: "Lima",
  },
  {
    utc: "GMT-05:00",
    value: "America/Guayaquil",
    group: "America",
    country: "Quito",
  },
  {
    utc: "GMT-04:00",
    value: "America/Halifax",
    group: "America",
    country: "Atlantic Time (Canada)",
  },
  {
    utc: "GMT-04:00",
    value: "America/Caracas",
    group: "America",
    country: "Caracas",
  },
  {
    utc: "GMT-04:00",
    value: "America/Guyana",
    group: "America",
    country: "Georgetown",
  },
  {
    utc: "GMT-04:00",
    value: "America/La_Paz",
    group: "America",
    country: "La Paz",
  },
  {
    utc: "GMT-04:00",
    value: "America/Puerto_Rico",
    group: "America",
    country: "Puerto Rico",
  },
  {
    utc: "GMT-04:00",
    value: "America/Santiago",
    group: "America",
    country: "Santiago",
  },
  {
    utc: "GMT-03:30",
    value: "America/St_Johns",
    group: "America",
    country: "Newfoundland",
  },
  {
    utc: "GMT-03:00",
    value: "America/Sao_Paulo",
    group: "America",
    country: "Brasilia",
  },
  {
    utc: "GMT-03:00",
    value: "America/Argentina/Buenos_Aires",
    group: "America",
    country: "Buenos Aires",
  },
  {
    utc: "GMT-03:00",
    value: "America/Montevideo",
    group: "America",
    country: "Montevideo",
  },
  {
    utc: "GMT-02:00",
    value: "America/Godthab",
    group: "America",
    country: "Greenland",
  },
  {
    utc: "GMT-02:00",
    value: "Etc/GMT+2",
    group: "Atlantic",
    country: "Mid-Atlantic",
  },
  {
    utc: "GMT-01:00",
    value: "Atlantic/Azores",
    group: "Atlantic",
    country: "Azores",
  },
  {
    utc: "GMT-01:00",
    value: "Atlantic/Cape_Verde",
    group: "Atlantic",
    country: "Cape Verde Is.",
  },
  {
    utc: "GMT+00:00",
    value: "Europe/London",
    group: "Europe",
    country: "Edinburgh",
  },
  {
    utc: "GMT+00:00",
    value: "Europe/Lisbon",
    group: "Europe",
    country: "Lisbon",
  },
  {
    utc: "GMT+00:00",
    value: "Europe/London",
    group: "Europe",
    country: "London",
  },
  {
    utc: "GMT+00:00",
    value: "Africa/Monrovia",
    group: "Africa",
    country: "Monrovia",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Amsterdam",
    group: "Europe",
    country: "Amsterdam",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Belgrade",
    group: "Europe",
    country: "Belgrade",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Berlin",
    group: "Europe",
    country: "Berlin",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Brussels",
    group: "Europe",
    country: "Brussels",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Budapest",
    group: "Europe",
    country: "Budapest",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Copenhagen",
    group: "Europe",
    country: "Copenhagen",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Madrid",
    group: "Europe",
    country: "Madrid",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Paris",
    group: "Europe",
    country: "Paris",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Prague",
    group: "Europe",
    country: "Prague",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Rome",
    group: "Europe",
    country: "Rome",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Sarajevo",
    group: "Europe",
    country: "Sarajevo",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Stockholm",
    group: "Europe",
    country: "Stockholm",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Vienna",
    group: "Europe",
    country: "Vienna",
  },
  {
    utc: "GMT+01:00",
    value: "Europe/Warsaw",
    group: "Europe",
    country: "Warsaw",
  },
  {
    utc: "GMT+01:00",
    value: "Africa/Lagos",
    group: "Africa",
    country: "West Central Africa",
  },
  {
    utc: "GMT+02:00",
    value: "Asia/Amman",
    group: "Asia",
    country: "Amman",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Athens",
    group: "Europe",
    country: "Athens",
  },
  {
    utc: "GMT+02:00",
    value: "Asia/Beirut",
    group: "Asia",
    country: "Beirut",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Bucharest",
    group: "Europe",
    country: "Bucharest",
  },
  {
    utc: "GMT+02:00",
    value: "Africa/Cairo",
    group: "Africa",
    country: "Cairo",
  },
  {
    utc: "GMT+02:00",
    value: "Africa/Harare",
    group: "Africa",
    country: "Harare",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Helsinki",
    group: "Europe",
    country: "Helsinki",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Istanbul",
    group: "Europe",
    country: "Istanbul",
  },
  {
    utc: "GMT+02:00",
    value: "Asia/Jerusalem",
    group: "Asia",
    country: "Jerusalem",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Kiev",
    group: "Europe",
    country: "Kyiv",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Minsk",
    group: "Europe",
    country: "Minsk",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Riga",
    group: "Europe",
    country: "Riga",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Sofia",
    group: "Europe",
    country: "Sofia",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Tallinn",
    group: "Europe",
    country: "Tallinn",
  },
  {
    utc: "GMT+02:00",
    value: "Europe/Vilnius",
    group: "Europe",
    country: "Vilnius",
  },
  {
    utc: "GMT+03:00",
    value: "Asia/Baghdad",
    group: "Asia",
    country: "Baghdad",
  },
  {
    utc: "GMT+03:00",
    value: "Asia/Kuwait",
    group: "Asia",
    country: "Kuwait",
  },
  {
    utc: "GMT+03:00",
    value: "Europe/Moscow",
    group: "Europe",
    country: "Moscow",
  },
  {
    utc: "GMT+03:00",
    value: "Africa/Nairobi",
    group: "Africa",
    country: "Nairobi",
  },
  {
    utc: "GMT+03:00",
    value: "Asia/Riyadh",
    group: "Asia",
    country: "Riyadh",
  },
  {
    utc: "GMT+03:30",
    value: "Asia/Tehran",
    group: "Asia",
    country: "Tehran",
  },
  {
    utc: "GMT+04:00",
    value: "Asia/Dubai",
    group: "Asia",
    country: "Abu Dhabi",
  },
  {
    utc: "GMT+04:00",
    value: "Asia/Baku",
    group: "Asia",
    country: "Baku",
  },
  {
    utc: "GMT+04:00",
    value: "Asia/Muscat",
    group: "Asia",
    country: "Muscat",
  },
  {
    utc: "GMT+04:00",
    value: "Asia/Tbilisi",
    group: "Asia",
    country: "Tbilisi",
  },
  {
    utc: "GMT+04:00",
    value: "Asia/Yerevan",
    group: "Asia",
    country: "Yerevan",
  },
  {
    utc: "GMT+04:30",
    value: "Asia/Kabul",
    group: "Asia",
    country: "Kabul",
  },
  {
    utc: "GMT+05:00",
    value: "Asia/Karachi",
    group: "Asia",
    country: "Islamabad",
  },
  {
    utc: "GMT+05:00",
    value: "Asia/Tashkent",
    group: "Asia",
    country: "Tashkent",
  },
  {
    utc: "GMT+05:30",
    value: "Asia/Kolkata",
    group: "Asia",
    country: "Chennai",
  },
  {
    utc: "GMT+05:30",
    value: "Asia/Kolkata",
    group: "Asia",
    country: "Kolkata",
  },
  {
    utc: "GMT+05:30",
    value: "Asia/Kolkata",
    group: "Asia",
    country: "Mumbai",
  },
  {
    utc: "GMT+05:30",
    value: "Asia/Kolkata",
    group: "Asia",
    country: "New Delhi",
  },
  {
    utc: "GMT+05:45",
    value: "Asia/Kathmandu",
    group: "Asia",
    country: "Kathmandu",
  },
  {
    utc: "GMT+06:00",
    value: "Asia/Almaty",
    group: "Asia",
    country: "Almaty",
  },
  {
    utc: "GMT+06:00",
    value: "Asia/Dhaka",
    group: "Asia",
    country: "Dhaka",
  },
  {
    utc: "GMT+06:00",
    value: "Asia/Yekaterinburg",
    group: "Asia",
    country: "Yekaterinburg",
  },
  {
    utc: "GMT+06:30",
    value: "Asia/Yangon",
    group: "Asia",
    country: "Yangon (Rangoon)",
  },
  {
    utc: "GMT+07:00",
    value: "Asia/Bangkok",
    group: "Asia",
    country: "Bangkok",
  },
  {
    utc: "GMT+07:00",
    value: "Asia/Hanoi",
    group: "Asia",
    country: "Hanoi",
  },
  {
    utc: "GMT+07:00",
    value: "Asia/Jakarta",
    group: "Asia",
    country: "Jakarta",
  },
  {
    utc: "GMT+07:00",
    value: "Asia/Novosibirsk",
    group: "Asia",
    country: "Novosibirsk",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Shanghai",
    group: "Asia",
    country: "Beijing",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Chongqing",
    group: "Asia",
    country: "Chongqing",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Hong_Kong",
    group: "Asia",
    country: "Hong Kong",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Krasnoyarsk",
    group: "Asia",
    country: "Krasnoyarsk",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Kuala_Lumpur",
    group: "Asia",
    country: "Kuala Lumpur",
  },
  {
    utc: "GMT+08:00",
    value: "Australia/Perth",
    group: "Australia",
    country: "Perth",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Singapore",
    group: "Asia",
    country: "Singapore",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Taipei",
    group: "Asia",
    country: "Taipei",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Ulaanbaatar",
    group: "Asia",
    country: "Ulaan Bataar",
  },
  {
    utc: "GMT+08:00",
    value: "Asia/Urumqi",
    group: "Asia",
    country: "Urumqi",
  },
  {
    utc: "GMT+09:00",
    value: "Asia/Irkutsk",
    group: "Asia",
    country: "Irkutsk",
  },
  {
    utc: "GMT+09:00",
    value: "Asia/Tokyo",
    group: "Asia",
    country: "Osaka",
  },
  {
    utc: "GMT+09:00",
    value: "Asia/Tokyo",
    group: "Asia",
    country: "Sapporo",
  },
  {
    utc: "GMT+09:00",
    value: "Asia/Seoul",
    group: "Asia",
    country: "Seoul",
  },
  {
    utc: "GMT+09:00",
    value: "Asia/Tokyo",
    group: "Asia",
    country: "Tokyo",
  },
  {
    utc: "GMT+09:30",
    value: "Australia/Adelaide",
    group: "Australia",
    country: "Adelaide",
  },
  {
    utc: "GMT+09:30",
    value: "Australia/Darwin",
    group: "Australia",
    country: "Darwin",
  },
  {
    utc: "GMT+10:00",
    value: "Australia/Brisbane",
    group: "Australia",
    country: "Brisbane",
  },
  {
    utc: "GMT+10:00",
    value: "Australia/Sydney",
    group: "Australia",
    country: "Canberra",
  },
  {
    utc: "GMT+10:00",
    value: "Pacific/Guam",
    group: "Pacific",
    country: "Guam",
  },
  {
    utc: "GMT+10:00",
    value: "Australia/Hobart",
    group: "Australia",
    country: "Hobart",
  },
  {
    utc: "GMT+10:00",
    value: "Australia/Melbourne",
    group: "Australia",
    country: "Melbourne",
  },
  {
    utc: "GMT+10:00",
    value: "Pacific/Port_Moresby",
    group: "Pacific",
    country: "Port Moresby",
  },
  {
    utc: "GMT+10:00",
    value: "Australia/Sydney",
    group: "Australia",
    country: "Sydney",
  },
  {
    utc: "GMT+11:00",
    value: "Asia/Magadan",
    group: "Asia",
    country: "Magadan",
  },
  {
    utc: "GMT+11:00",
    value: "Pacific/Noumea",
    group: "Pacific",
    country: "New Caledonia",
  },
  {
    utc: "GMT+11:00",
    value: "Pacific/Guadalcanal",
    group: "Pacific",
    country: "Solomon Is.",
  },
  {
    utc: "GMT+12:00",
    value: "Pacific/Auckland",
    group: "Pacific",
    country: "Auckland",
  },
  {
    utc: "GMT+12:00",
    value: "Pacific/Fiji",
    group: "Pacific",
    country: "Fiji",
  },
  {
    utc: "GMT+12:00",
    value: "Asia/Kamchatka",
    group: "Asia",
    country: "Kamchatka",
  },
  {
    utc: "GMT+12:00",
    value: "Pacific/Majuro",
    group: "Pacific",
    country: "Marshall Is.",
  },
  {
    utc: "GMT+12:00",
    value: "Pacific/Auckland",
    group: "Pacific",
    country: "Wellington",
  },
  {
    utc: "GMT+13:00",
    value: "Pacific/Tongatapu",
    group: "Pacific",
    country: "Nuku'alofa",
  },
  {
    utc: "GMT+13:00",
    value: "Pacific/Apia",
    group: "Pacific",
    country: "Samoa",
  },
  {
    utc: "GMT+13:00",
    value: "Pacific/Fakaofo",
    group: "Pacific",
    country: "Tokelau Is.",
  },
];
