{
 "title": "Default Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "cluster_id", "label": "ClusterId" }
  ]
 },
 "panels": [
  { "title": "Ray Scheduler Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduler Task State",
   "type": "graph",
   "description": "Current number of tasks currently in a particular state.\n\nState: the task state, as described by rpc::TaskState proto in common.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(ray_tasks{State=~\"FINISHED|FAILED\"}[14d])) by (State) or clamp_min(sum(ray_tasks{State!~\"FINISHED|FAILED\"}) by (State), 0)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Scheduler Actor State",
   "type": "graph",
   "description": "Current number of actors currently in a particular state.\n\nState: the actor state, as described by rpc::ActorTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    { "expr": "sum(ray_actors) by (State)", "legendFormat": "{{State}}" }
   ]
  },
  {
   "title": "Scheduler Object Store Memory",
   "type": "graph",
   "description": "Ray's object store memory usage. The dotted line indicates the maximum amount of object store memory from the cluster. \n\nThe total object store memory is dynamically decided by Ray based on the available memory when Ray starts (`ray start`) unless --object-store-memory is specified.\n\nRay objects can be in 3 different states. \n\nUNSEALED: Object is being written to the object store.\n\nIN_MEMORY: Object is in shared memory.\n\nSPILLED: Object is spilled to a disk because the shared memory is full. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory / 1e9) by (Location)",
     "legendFormat": "{{Location}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"object_store_memory\"} / 1e9)",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Scheduler CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPU usage of Ray. The dotted line indicates the total number of CPUs. The logical CPU is allocated by `num_cpus` arguments from tasks and actors. \n\nNOTE: Ray's logical CPU is different from physical CPU usage. Ray's logical CPU is allocated by `num_cpus` arguments.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "ray_resources{Name=\"CPU\",State=\"USED\",instance=~\"$Instance\"}",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"CPU\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Scheduler GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPU usage of Ray. The dotted line indicates the total number of GPUs. The logical GPU is allocated by `num_gpus` arguments from tasks and actors. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_resources{Name=\"GPU\",State=\"USED\"}",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"GPU\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  { "title": "Node Hardware Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Node CPU (hardware utilization)",
   "type": "graph",
   "description": "Node's physical (hardware) CPU usage. The dotted line means the total number of hardware CPUs from the cluster. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "ray_node_cpu_utilization{instance=~\"$Instance\",cluster_id=\"$cluster_id\"} * ray_node_cpu_count{instance=~\"$Instance\",cluster_id=\"$cluster_id\"} / 100",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_node_cpu_count{cluster_id=\"$cluster_id\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU (hardware utilization)",
   "type": "graph",
   "description": "Node's physical (hardware) GPU usage. The dotted line means the total number of hardware GPUs from the cluster. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\",cluster_id=\"$cluster_id\"} / 100",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_node_gpus_available{cluster_id=\"$cluster_id\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "graph",
   "description": "Node's physical (hardware) disk usage. The dotted line means the total amount of disk space from the cluster.\n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\",cluster_id=\"$cluster_id\"}",
     "legendFormat": "Disk Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_disk_free{cluster_id=\"$cluster_id\"}) + sum(ray_node_disk_usage{cluster_id=\"$cluster_id\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Memory (heap + object store)",
   "type": "graph",
   "description": "The physical (hardware) memory usage for each node. The dotted line means the total amount of memory from the cluster. Node memory is a sum of object store memory (shared memory) and heap memory.\n\nNote: If Ray is deployed within a container, the total memory could be lower than the host machine because Ray may reserve some additional memory space outside the container.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_mem_used{instance=~\"$Instance\",cluster_id=\"$cluster_id\"}",
     "legendFormat": "Memory Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_mem_total{cluster_id=\"$cluster_id\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU Memory (GRAM)",
   "type": "graph",
   "description": "The physical (hardware) GPU memory usage for each node. The dotted line means the total amount of GPU memory from the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\",cluster_id=\"$cluster_id\"} * 1024 * 1024",
     "legendFormat": "Used GRAM: {{instance}}"
    },
    {
     "expr": "(sum(ray_node_gram_available{cluster_id=\"$cluster_id\"}) + sum(ray_node_gram_used{cluster_id=\"$cluster_id\"})) * 1024 * 1024",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Memory by Component",
   "type": "graph",
   "description": "The physical (hardware) memory usage across the cluster, broken down by component. This reports the summed USS (unique set size) per Ray component.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_uss_mb * 1e6) by (Component)",
     "legendFormat": "{{Component}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "A total number of active failed, and pending nodes from the cluster. \n\nACTIVE: A node is alive and available.\n\nFAILED: A node is dead and not available. The node is considered dead when the raylet process on the node is terminated. The node will get into the failed state if it cannot be provided (e.g., there's no available node from the cloud provider) or failed to setup (e.g., setup_commands have errors). \n\nPending: A node is being started by the Ray cluster launcher. The node is unavailable now because it is being provisioned and initialized.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "ray_cluster_active_nodes{cluster_id=\"$cluster_id\"}",
     "legendFormat": "Active Nodes ({{node_type}})"
    },
    {
     "expr": "ray_cluster_failed_nodes{cluster_id=\"$cluster_id\"}",
     "legendFormat": "Failed Nodes {{node_type}}"
    },
    {
     "expr": "ray_cluster_pending_nodes{cluster_id=\"$cluster_id\"}",
     "legendFormat": "Pending Nodes ({{node_type}})"
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "graph",
   "description": "Network speed per node.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "ray_node_network_receive_speed{instance=~\"$Instance\",cluster_id=\"$cluster_id\"}",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "ray_node_network_send_speed{instance=~\"$Instance\",cluster_id=\"$cluster_id\"}",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_io_write_speed{instance=~\"$Instance\",cluster_id=\"$cluster_id\"}",
     "legendFormat": "Write: {{instance}}"
    },
    {
     "expr": "ray_node_disk_io_read_speed{instance=~\"$Instance\",cluster_id=\"$cluster_id\"}",
     "legendFormat": "Read: {{instance}}"
    }
   ]
  }
 ]
}