#ifndef RAY_OBJECT_MANAGER_OBJECT_MANAGER_PROTOCOL_H
#define RAY_OBJECT_MANAGER_OBJECT_MANAGER_PROTOCOL_H

// TODO(hme): Move all messaging code here.

#endif  // RAY_OBJECT_MANAGER_OBJECT_MANAGER_PROTOCOL_H
