# Examples

py_test(
    name = "example_apex_dqn_cartpole_v1",
    size = "large",
    srcs = ["examples/apex_dqn_cartpole_v1.py"],
    args = ["--run-as-test"],
    main = "apex_dqn_cartpole_v1.py",
    tags = [
        "example",
        "team:rllib",
    ],
)

# Learning Tests

# Compilation Tests

py_test(
    name = "test_apex_dqn",
    size = "large",
    srcs = ["tests/test_apex_dqn.py"],
    tags = [
        "algorithms_dir",
        "team:rllib",
    ],
)
