# Examples

py_test(
    name = "example_apex_dqn_cartpole_v1",
    main = "apex_dqn_cartpole_v1.py",
    tags = ["team:rllib", "example"],
    size = "large",
    srcs = ["examples/apex_dqn_cartpole_v1.py"],
    args = ["--run-as-test"]
)

# Learning Tests

# Compilation Tests

py_test(
    name = "test_apex_dqn",
    tags = ["team:rllib", "algorithms_dir"],
    size = "large",
    srcs = ["tests/test_apex_dqn.py"]
)
