{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Build a tool-using agent\n",
        "\n",
        "This tutorial guides you through building and deploying a sophisticated, tool-using agent using LangChain, LangGraph, and Ray Serve on Anyscale.\n",
        "\n",
        "Learn how to create a scalable microservices architecture where each component—the agent, the LLM, and the tools—runs as an independent, autoscaling service:\n",
        "\n",
        "* The Agent (built with LangGraph) orchestrates tasks and manages conversation state.\n",
        "\n",
        "* The LLM (Qwen 4&nbsp;B) runs in its own service for dedicated, high-speed inference.\n",
        "\n",
        "* The Tools (a weather API) expose themselves through the Model Context Protocol (MCP), an open standard that allows the agent to discover and use them dynamically.\n",
        "\n",
        "This decoupled design provides automatic scaling, fault isolation, and the flexibility to update or swap components such as LLMs or tools without changing your agent's code.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Architecture overview\n",
        "\n",
        "You can build the agentic system from three core components, each running as its own Ray Serve application.\n",
        "\n",
        "### Components\n",
        "* Agent Service ([LangChain agents](https://docs.langchain.com/oss/python/langchain/agents)): The \"brain\" of the operation. It orchestrates the multi-step reasoning and manages the conversation state. It's lightweight (CPU-only) and deployed with Ray Serve. **Note:**  [LangGraph v1 deprecates the `createReactAgent` prebuilt](https://docs.langchain.com/oss/javascript/migrate/langgraph-v1#deprecation:-createreactagent-%E2%86%92-createagent). Use LangChain's `create_agent`, which runs on LangGraph and adds a flexible middle-ware system. \n",
        "\n",
        "\n",
        "* LLM Service (Ray Serve LLM): The \"language engine.\" It runs the `Qwen/Qwen3-4B-Instruct-2507-FP8` model, optimized for tool use. It's deployed with vLLM on a GPU (L4) for high-speed inference and provides an OpenAI-compatible API.\n",
        "\n",
        "* Tool Service (MCP): The \"hands.\" It exposes a weather API as a set of tools. The agent discovers these tools at runtime using the Model Context Protocol (MCP). It's also a stateless, CPU-only service.\n",
        "\n",
        "<div align=\"center\">\n",
        "    <img src=\"https://anyscale-public-materials.s3.us-west-2.amazonaws.com/agent-template/overall-architecture.svg\" alt=\"Overall Architecture\" width=\"95%\"/>\n",
        "</div>\n",
        "\n",
        "### Benefits of this architecture\n",
        "\n",
        "This architecture allows each component to scale independently. Your GPU-intensive LLM service can scale up and down based on inference demand, separate from the lightweight, CPU-based agent orchestration.\n",
        "\n",
        "### Key benefits using Ray and Anyscale include:\n",
        "\n",
        "* Independent scaling: Scale GPUs for the LLM and CPUs for the agent/tools separately.\n",
        "\n",
        "* High availability: Zero-downtime updates and automatic recovery from failures.\n",
        "\n",
        "* Flexibility: Swap LLMs or add new tools simply by deploying a new service. The agent discovers them at runtime—no code changes needed.\n",
        "\n",
        "* Enhanced observability: Anyscale provides comprehensive logs, metrics, and tracing for each service.\n",
        "\n",
        "### Additional resources\n",
        "\n",
        "For more information on LLM serving and Ray Serve, see the following:\n",
        "- [Anyscale LLM Serving documentation](https://docs.anyscale.com/llm/serving)\n",
        "- [Ray Serve LLM documentation](https://docs.ray.io/en/master/serve/llm/index.html)\n",
        "- [Anyscale LLM Serving Template](https://console.anyscale.com/template-preview/deployment-serve-llm)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "\n",
        "\n",
        "## Dependencies and compute resource requirements\n",
        "\n",
        "**Docker Image:** For optimal compatibility and performance, use the Docker image `anyscale/ray-llm:2.52.0-py311-cu128`. This image includes Ray 2.52.0, Python 3.11, and CUDA 12.8 support, providing all necessary dependencies for LLM serving with GPU acceleration.\n",
        "\n",
        "**GPU Requirements:** The deployment requires two compute resources: one L4 GPU (g6.2xlarge instance, 24 GB GPU memory) for the LLM service, and one m5d.xlarge (4 vCPU) for the MCP and agent services.\n",
        "\n",
        "**Python Libraries**: This project uses `requirements.txt` for dependency management. Run the following command to install dependencies:\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "shellscript"
        }
      },
      "outputs": [],
      "source": [
        "%%bash\n",
        "# Install dependencies\n",
        "pip install -r requirements.txt"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Implementation: Building the services\n",
        "\n",
        "This project consists of several Python scripts that work together to create and serve the agent.\n",
        "\n",
        "### Step 1: Create the LLM service\n",
        "\n",
        "Check out the code in `llm_deploy_qwen.py`. This script deploys the Qwen LLM (`Qwen/Qwen3-4B-Instruct-2507-FP8`) as an OpenAI-compatible API endpoint using Ray Serve's `build_openai_app` utility. This allows you to use the Qwen model with any OpenAI-compatible client, including LangChain.\n",
        "\n",
        "The following are key configurations in this script:\n",
        "\n",
        "- **`accelerator_type=\"L4\"`**: Specifies the GPU type. L4 GPUs (Ada Lovelace architecture) are optimized for FP8 precision, making them cost-effective for this quantized model. For higher throughput, use H100 GPUs. For GPU selection guidance, see the [GPU guidance documentation](https://docs.anyscale.com/llm/serving/gpu-guidance).\n",
        "\n",
        "\n",
        "- **`enable_auto_tool_choice=True`**: Enables the model to automatically decide when to use tools based on the input. This is essential for agent workflows where the LLM needs to determine whether to call a tool or respond directly. For more information on tool calling, see the [tool and function calling documentation](https://docs.anyscale.com/llm/serving/tool-function-calling).\n",
        "\n",
        "- **`tool_call_parser=\"hermes\"`**: Specifies the parsing strategy for tool calls. The `hermes` parser is designed for models that follow the Hermes function-calling format, which Qwen models support.\n",
        "\n",
        "- **`trust_remote_code=True`**: Required when loading Qwen models from Hugging Face, as they use custom chat templates and tokenization logic that aren't part of the standard transformers library.\n",
        "\n",
        "**Additional LLM development resources:**\n",
        "- [LLM serving basics](https://docs.anyscale.com/llm/serving/intro)\n",
        "- [LLM serving examples and template](https://console.anyscale.com/template-preview/deployment-serve-llm): Comprehensive examples for deploying LLMs with Ray Serve\n",
        "- [Performance optimization documentation](https://docs.anyscale.com/llm/serving/performance-optimization)\n",
        "- [Configure structured output](https://docs.anyscale.com/llm/serving/structured-output): Ensure LLM responses match specific schemas\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Step 2: Create the MCP weather tool service\n",
        "\n",
        "Check out the code in `weather_mcp_ray.py` to deploy weather tools as an MCP (Model Context Protocol) service.\n",
        "\n",
        "**How the weather tool service works:**\n",
        "\n",
        "The `weather_mcp_ray.py` script uses `FastMCP` to define and expose weather-related tools. This service is a FastAPI application deployed with Ray Serve, making the tools available over HTTP.\n",
        "\n",
        "- **FastMCP framework**: The `FastMCP` class provides a way to define tools using Python decorators. Setting `stateless_http=True` makes it suitable for deployment as an HTTP service.\n",
        "\n",
        "- **Tool registration**: Each function decorated with `@mcp.tool()` becomes an automatically discoverable tool:\n",
        "  - `get_alerts(state: str)`: Fetches active weather alerts for a given U.S. state code.\n",
        "  - `get_forecast(latitude: float, longitude: float)`: Retrieves a 5-period forecast for specific coordinates.\n",
        "\n",
        "- **Tool metadata**: The docstrings for each tool function serve as descriptions that the agent uses to understand when and how to call each tool. This is crucial for the LLM to decide which tool to use.\n",
        "\n",
        "- **Ray Serve deployment**: When deployed with Ray Serve, this becomes a scalable microservice that can handle multiple concurrent tool requests from agent instances.\n",
        "\n",
        ":::{note}\n",
        "Ray Serve only supports stateless HTTP mode in MCP. Set `stateless_http=True` to prevent \"session not found\" errors when multiple replicas are running:\n",
        ":::\n",
        "\n",
        "```python\n",
        "mcp = FastMCP(\"weather\", stateless_http=True)\n",
        "```\n",
        "\n",
        "**Additional resources:**\n",
        "- [MCP quickstart guide](https://docs.anyscale.com/mcp/mcp-quickstart-guide)\n",
        "- [Deploy scalable MCP servers](https://docs.anyscale.com/mcp/scalable-remote-mcp-deployment)\n",
        "- [Anyscale MCP Deployment Template](https://console.anyscale.com/template-preview/mcp-ray-serve)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Step 3: Create the agent logic\n",
        "\n",
        "<div align=\"center\">\n",
        "  <img src=\"https://anyscale-public-materials.s3.us-west-2.amazonaws.com/agent-template/agent-architecture.svg\" alt=\"Agent Architecture\" width=\"75%\"/>\n",
        "</div>\n",
        "\n",
        "Check out the code in `agent_with_mcp.py` to define the agent that orchestrates the LLM and tools.\n",
        "\n",
        "The core function is `build_agent`:\n",
        "\n",
        "```python\n",
        "# ========== BUILD AGENT ==========\n",
        "async def build_agent():\n",
        "    \"\"\"Instantiate an agent with MCP tools when available.\"\"\"\n",
        "    mcp_tools = await get_mcp_tools()\n",
        "\n",
        "    tools = list(mcp_tools)\n",
        "    print(f\"\\n[Agent] Using {len(tools)} tool(s).\")\n",
        "\n",
        "    memory = MemorySaver()\n",
        "    agent = create_agent(\n",
        "        llm,\n",
        "        tools,\n",
        "        system_prompt=PROMPT,\n",
        "        checkpointer=memory,\n",
        "    )\n",
        "    return agent\n",
        "```\n",
        "\n",
        "**How the agent works:**\n",
        "\n",
        "- **LLM configuration**: Connects to your deployed Qwen model using the OpenAI-compatible API.\n",
        "\n",
        "- **Tool discovery**: The function `get_mcp_tools` uses `MultiServerMCPClient` to automatically discover available tools from the MCP service.\n",
        "\n",
        "- **Agent creation**: Creates an agent with the LLM, tools, and system prompt using LangChain's `create_agent` function.\n",
        "\n",
        "- **Memory management**: Uses `MemorySaver` to maintain conversation state across multiple turns.\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Step 4: Create the agent deployment script\n",
        "\n",
        "The `ray_serve_agent_deployment.py` script deploys the agent as a Ray Serve application with a `/chat` endpoint.\n",
        "\n",
        "```python\n",
        "import json\n",
        "from contextlib import asynccontextmanager\n",
        "from typing import AsyncGenerator\n",
        "from uuid import uuid4\n",
        "\n",
        "from fastapi import FastAPI, Request\n",
        "from fastapi.encoders import jsonable_encoder\n",
        "from starlette.responses import StreamingResponse\n",
        "from ray import serve\n",
        "\n",
        "from agent_with_mcp import build_agent  # Your factory that returns a LangChain / LangGraph agent.\n",
        "\n",
        "# ----------------------------------------------------------------------\n",
        "# FastAPI app with an async lifespan hook.\n",
        "# ----------------------------------------------------------------------\n",
        "@asynccontextmanager\n",
        "async def lifespan(app: FastAPI):\n",
        "    agent = await build_agent()  # Likely compiled with a checkpointer.\n",
        "    app.state.agent = agent\n",
        "    try:\n",
        "        yield\n",
        "    finally:\n",
        "        if hasattr(agent, \"aclose\"):\n",
        "            await agent.aclose()\n",
        "\n",
        "fastapi_app = FastAPI(lifespan=lifespan)\n",
        "\n",
        "@fastapi_app.post(\"/chat\")\n",
        "async def chat(request: Request):\n",
        "    \"\"\"\n",
        "    POST /chat\n",
        "    Body: {\"user_request\": \"<text>\", \"thread_id\": \"<optional>\", \"checkpoint_ns\": \"<optional>\"}\n",
        "\n",
        "    Streams LangGraph 'update' dicts as SSE (one JSON object per event).\n",
        "    \"\"\"\n",
        "    body = await request.json()\n",
        "    user_request: str = body.get(\"user_request\", \"\")\n",
        "\n",
        "    # Threading and checkpoint identifiers.\n",
        "    thread_id = (\n",
        "        body.get(\"thread_id\")\n",
        "        or request.headers.get(\"X-Thread-Id\")\n",
        "        or str(uuid4())  # New thread per request if none provided.\n",
        "    )\n",
        "    checkpoint_ns = body.get(\"checkpoint_ns\")  # Optional namespacing.\n",
        "\n",
        "    # Build config for LangGraph.\n",
        "    config = {\"configurable\": {\"thread_id\": thread_id}}\n",
        "    if checkpoint_ns:\n",
        "        config[\"configurable\"][\"checkpoint_ns\"] = checkpoint_ns\n",
        "\n",
        "    async def event_stream() -> AsyncGenerator[str, None]:\n",
        "        agent = request.app.state.agent\n",
        "        inputs = {\"messages\": [{\"role\": \"user\", \"content\": user_request}]}\n",
        "\n",
        "        try:\n",
        "            # Stream updates from the agent.\n",
        "            async for update in agent.astream(inputs, config=config, stream_mode=\"updates\"):\n",
        "                safe_update = jsonable_encoder(update)\n",
        "                # Proper SSE framing: \"data: <json>\\n\\n\".\n",
        "                yield f\"data: {json.dumps(safe_update)}\\n\\n\"\n",
        "        except Exception as e:\n",
        "            # Don't crash the SSE; surface one terminal error event and end.\n",
        "            err = {\"error\": type(e).__name__, \"detail\": str(e)}\n",
        "            yield f\"data: {json.dumps(err)}\\n\\n\"\n",
        "\n",
        "    # Expose thread id so the client can reuse it on the next call.\n",
        "    headers = {\"X-Thread-Id\": thread_id}\n",
        "\n",
        "    return StreamingResponse(\n",
        "        event_stream(),\n",
        "        media_type=\"text/event-stream\",\n",
        "        headers=headers,\n",
        "    )\n",
        "\n",
        "# ----------------------------------------------------------------------\n",
        "# Ray Serve deployment wrapper.\n",
        "# ----------------------------------------------------------------------\n",
        "@serve.deployment(ray_actor_options={\"num_cpus\": 1})\n",
        "@serve.ingress(fastapi_app)\n",
        "class LangGraphServeDeployment:\n",
        "    pass\n",
        "\n",
        "app = LangGraphServeDeployment.bind()\n",
        "\n",
        "# Deploy the agent app locally:\n",
        "# serve run ray_serve_agent_deployment:app\n",
        "\n",
        "# Deploy the agent using Anyscale service:\n",
        "# anyscale service deploy ray_serve_agent_deployment:app\n",
        "```\n",
        "\n",
        "**How deployment works:**\n",
        "\n",
        "- **FastAPI lifespan management**: Uses `@asynccontextmanager` to initialize the agent on startup and clean up on shutdown.\n",
        "\n",
        "- **Streaming endpoint**: The `/chat` endpoint accepts POST requests and returns server-sent events (SSE):\n",
        "  ```python\n",
        "  {\n",
        "    \"user_request\": \"What's the weather?\",\n",
        "    \"thread_id\": \"optional-thread-id\",\n",
        "    \"checkpoint_ns\": \"optional-namespace\"\n",
        "  }\n",
        "  ```\n",
        "\n",
        "- **Thread management**: Each conversation can have a `thread_id` to maintain context across requests. If you don't provide a `thread_id`, the system generates a new UUID.\n",
        "\n",
        "- **Event streaming**: Uses LangGraph's `astream` to emit real-time updates (tool calls, reasoning steps, final answers) as JSON objects.\n",
        "\n",
        "- **Resource allocation**: The agent deployment is lightweight (0.2 CPUs per replica, no GPU) since heavy computation happens in the LLM service.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Deploy the services\n",
        "\n",
        "Now that you've reviewed the code, deploy each service to Anyscale.\n",
        "\n",
        "### Step 5: Deploy the LLM service\n",
        "\n",
        "Deploy the Qwen LLM service on Anyscale. This command creates a scalable endpoint for LLM inference:\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "shellscript"
        }
      },
      "outputs": [],
      "source": [
        "%%bash\n",
        "anyscale service deploy llm_deploy_qwen:app --name llm_deploy_qwen_service\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "After deployment completes, you receive:\n",
        "- Service URL (for example, `https://llm-deploy-qwen-service-jgz99.cld-kvedzwag2qa8i5bj.s.anyscaleuserdata.com`)\n",
        "- API token for authentication\n",
        "\n",
        "**Save these values to configure the agent later.** Note: You don't need to add `/v1` to the URL manually; the code uses `urljoin` to append it automatically.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Step 6: Deploy the weather MCP service\n",
        "\n",
        "Deploy the weather tool service. This creates an endpoint for the agent to discover and call weather tools:\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "shellscript"
        }
      },
      "outputs": [],
      "source": [
        "%%bash\n",
        "anyscale service deploy weather_mcp_ray:app --name weather_mcp_service\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "After deployment completes, you receive:\n",
        "- Service URL (for example, `https://weather-mcp-service-jgz99.cld-kvedzwag2qa8i5bj.s.anyscaleuserdata.com`)\n",
        "- API token for authentication\n",
        "\n",
        "**Note:** You don't need to add `/mcp` to the URL manually; the code uses `urljoin` to append it automatically.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Step 7: Configure the agent\n",
        "\n",
        "Update `agent_with_mcp.py` with the service endpoints you received from the deployments. Modify the following lines:\n",
        "\n",
        "```python\n",
        "from urllib.parse import urljoin\n",
        "\n",
        "API_KEY = \"<your-llm-service-token>\"\n",
        "OPENAI_COMPAT_BASE_URL = \"<your-llm-service-url>\"  \n",
        "MODEL = \"Qwen/Qwen3-4B-Instruct-2507-FP8\"\n",
        "TEMPERATURE = 0.01\n",
        "WEATHER_MCP_BASE_URL = \"<your-mcp-service-url>\"  \n",
        "WEATHER_MCP_TOKEN = \"<your-mcp-service-token>\"\n",
        "\n",
        "# The code uses urljoin to automatically append /v1 and /mcp:\n",
        "llm = ChatOpenAI(\n",
        "    model=MODEL,\n",
        "    base_url=urljoin(OPENAI_COMPAT_BASE_URL, \"v1\"),\n",
        "    api_key=API_KEY,\n",
        "    ...\n",
        ")\n",
        "\n",
        "mcp_client = MultiServerMCPClient({\n",
        "    \"weather\": {\n",
        "        \"url\": urljoin(WEATHER_MCP_BASE_URL, \"mcp\"),\n",
        "        ...\n",
        "    }\n",
        "})\n",
        "```\n",
        "\n",
        "\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Step 8: Deploy the agent service locally\n",
        "\n",
        "Deploy the agent itself. For local testing, use `serve run` in your terminal. For production deployment on Anyscale, see next step.\n",
        "\n",
        "**For local deployment:**\n",
        "\n",
        "```bash\n",
        "serve run ray_serve_agent_deployment:app  \n",
        "```\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Test the agent\n",
        "\n",
        "### Step 9: Send test requests\n",
        "\n",
        "With the agent service running, send requests to the `/chat` endpoint. \n",
        "The script \"helpers/agent_client_local.py\" sends a request and streams the response:\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "import requests\n",
        "\n",
        "SERVER_URL = \"http://127.0.0.1:8000/chat\"  # For local deployment.\n",
        "HEADERS = {\"Content-Type\": \"application/json\"}\n",
        "\n",
        "def chat(user_request: str, thread_id: str | None = None) -> None:\n",
        "    \"\"\"Send a chat request to the agent and stream the response.\"\"\"\n",
        "    payload = {\"user_request\": user_request}\n",
        "    if thread_id:\n",
        "        payload[\"thread_id\"] = thread_id\n",
        "\n",
        "    with requests.post(SERVER_URL, headers=HEADERS, json=payload, stream=True) as resp:\n",
        "        resp.raise_for_status()\n",
        "        # Capture thread_id for multi-turn conversations.\n",
        "        server_thread = resp.headers.get(\"X-Thread-Id\")\n",
        "        if not thread_id and server_thread:\n",
        "            print(f\"[thread_id: {server_thread}]\")\n",
        "        # Stream SSE events.\n",
        "        for line in resp.iter_lines():\n",
        "            if not line:\n",
        "                continue\n",
        "            txt = line.decode(\"utf-8\")\n",
        "            if txt.startswith(\"data: \"):\n",
        "                txt = txt[len(\"data: \"):]\n",
        "            print(txt, flush=True)\n",
        "\n",
        "# Test the agent.\n",
        "chat(\"What's the weather in Palo Alto?\")\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Terminate the local server\n",
        "After testing the agent locally, you can shut down the local server by pressing `Ctrl + C` in the same terminal, or by running the following command in a different terminal:\n",
        "\n",
        "```bash\n",
        "serve shutdown -y\n",
        "```"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Step 10: Deploy the agent to production on Anyscale\n",
        "\n",
        "After testing the agent locally, deploy it to Anyscale for production use. This creates a scalable, managed endpoint with enterprise features.\n",
        "\n",
        "#### Why deploy to Anyscale\n",
        "\n",
        "**Production benefits:**\n",
        "- **Auto-scaling**: Automatically scales replicas based on request volume (0 to N replicas)\n",
        "- **High availability**: Zero-downtime deployments with automated handling of outages\n",
        "- **Observability**: Built-in metrics, logs, and distributed tracing\n",
        "- **Cost optimization**: Scale to zero when idle (with appropriate configuration)\n",
        "- **Load balancing**: Distributes requests across multiple agent replicas\n",
        "- **Fault isolation**: Agent, LLM, and tools run as separate services\n",
        "\n",
        "#### Deploy the agent service\n",
        "\n",
        "Run the following command to deploy your agent to Anyscale. This command packages your code and creates a production-ready service:\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "shellscript"
        }
      },
      "outputs": [],
      "source": [
        "%%bash\n",
        "anyscale service deploy ray_serve_agent_deployment:app --name agent_service_langchain"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "#### Understanding the deployment output\n",
        "\n",
        "After running the deployment command, you receive:\n",
        "- **Service URL**: The HTTPS endpoint for your agent (for example, `https://agent-service-langchain-jgz99.cld-kvedzwag2qa8i5bj.s.anyscaleuserdata.com`)\n",
        "- **Authorization token**: Bearer token for authenticating requests\n",
        "- **Service UI link**: Direct link to monitor your service in the Anyscale console\n",
        "\n",
        "#### Test the production agent\n",
        "\n",
        "Once deployed, test your production agent with authenticated requests. Update the following code with your deployment details.\n",
        "\n",
        "**Note:** The repository also includes the script at \"helpers/agent_client_anyscale.py\" for your reference."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "import requests\n",
        "\n",
        "base_url = \"https://agent-service-langchain-jgz99.cld-kvedzwag2qa8i5bj.s.anyscaleuserdata.com\" ## replace with your service url\n",
        "token = \"nZp2BEjdloNlwGyxoWSpdalYGtkhfiHtfXhmV4BQuyk\" ## replace with your service bearer token\n",
        "\n",
        "SERVER_URL = f\"{base_url}/chat\"  # For Anyscale deployment.\n",
        "HEADERS = {\"Content-Type\": \"application/json\",\n",
        "\"Authorization\": f\"Bearer {token}\"\n",
        "}\n",
        "\n",
        "def chat(user_request: str, thread_id: str | None = None) -> None:\n",
        "    \"\"\"Send a chat request to the agent and stream the response.\"\"\"\n",
        "    payload = {\"user_request\": user_request}\n",
        "    if thread_id:\n",
        "        payload[\"thread_id\"] = thread_id\n",
        "\n",
        "    with requests.post(SERVER_URL, headers=HEADERS, json=payload, stream=True) as resp:\n",
        "        resp.raise_for_status()\n",
        "        # Capture thread_id for multi-turn conversations.\n",
        "        server_thread = resp.headers.get(\"X-Thread-Id\")\n",
        "        if not thread_id and server_thread:\n",
        "            print(f\"[thread_id: {server_thread}]\")\n",
        "        # Stream SSE events.\n",
        "        for line in resp.iter_lines():\n",
        "            if not line:\n",
        "                continue\n",
        "            txt = line.decode(\"utf-8\")\n",
        "            if txt.startswith(\"data: \"):\n",
        "                txt = txt[len(\"data: \"):]\n",
        "            print(txt, flush=True)\n",
        "\n",
        "# Test the agent.\n",
        "chat(\"What's the weather in Palo Alto?\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Terminate the production server\n",
        "Right now there are three production services running: `llm_deploy_qwen_service`, `weather_mcp_service`, and `agent_service_langchain`. You can manually shutdown them on the service page, or you can run the command in your terminal to shutdown them.\n",
        "\n",
        "```bash\n",
        "anyscale service terminate -n llm_deploy_qwen_service\n",
        "anyscale service terminate -n weather_mcp_service\n",
        "anyscale service terminate -n agent_service_langchain\n",
        "```"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Next steps\n",
        "\n",
        "You've successfully built, deployed, and tested a multi-tool agent using Ray Serve on Anyscale. This architecture demonstrates how to build production-ready AI applications with independent scaling, fault isolation, and dynamic tool discovery.\n",
        "\n",
        "### Extend your agent\n",
        "\n",
        "**Add more tools**  \n",
        "Extend the MCP service with additional capabilities such as database queries, API integrations, or custom business logic. The MCP protocol allows your agent to discover new tools dynamically without code changes. For implementation examples, see the [Anyscale MCP Deployment Template](https://console.anyscale.com/template-preview/mcp-ray-serve).\n",
        "\n",
        "**Swap or upgrade LLMs**  \n",
        "Replace the Qwen model with other tool-calling models such as GPT-4, Claude, or Llama variants. Since the LLM runs as a separate service, you can A/B test different models or perform zero-downtime upgrades. For deployment patterns, see the [Anyscale LLM Serving Template](https://console.anyscale.com/template-preview/deployment-serve-llm).\n",
        "\n",
        "**Build complex workflows**  \n",
        "Implement sophisticated reasoning patterns with LangGraph, such as multi-agent collaboration, iterative refinement, or conditional branching based on tool outputs.\n",
        "\n",
        "### Optimize for production\n",
        "\n",
        "**Monitor performance**  \n",
        "Use Anyscale's built-in observability to track:\n",
        "- Request latency and token throughput\n",
        "- GPU utilization and memory usage\n",
        "- Memory or disk usage\n",
        "- Node count\n",
        "\n",
        "To enable LLM metrics, see [Monitor with the Ray Serve LLM dashboard](https://docs.anyscale.com/llm/serving/benchmarking/metrics#monitor-with-the-ray-serve-llm-dashboard). Note: Engine metric logging is on by default as of Ray 2.51 or later.\n",
        "For detailed metrics guidance on monitoring with Anyscale service, see [Monitor a service](https://docs.anyscale.com/services/monitoring#metrics).\n",
        "\n",
        "\n",
        "**Scale efficiently**  \n",
        "Configure auto-scaling policies for each service independently:\n",
        "- Scale the LLM service based on GPU utilization\n",
        "- Scale the agent service based on request volume\n",
        "- Scale tool services based on specific workload patterns\n",
        "\n",
        "See [Ray Serve autoscaling configuration](https://docs.anyscale.com/llm/serving/parameter-tuning#ray-serve-autoscaling-configuration)\n",
        "\n",
        "### Production best practices\n",
        "\n",
        "Anyscale services provide enterprise-grade features for running agents in production. Key capabilities include:\n",
        "\n",
        "- **Zero-downtime deployments**: Update models or agent logic without interrupting service. See [Update an Anyscale service](https://docs.anyscale.com/services/update).\n",
        "\n",
        "- **Multi-version management**: Deploy up to 10 versions behind a single endpoint for A/B testing and canary deployments. See [Deploy multiple versions of an Anyscale service](https://docs.anyscale.com/services/versions).\n",
        "\n",
        "- **High availability**: Distribute replicas across availability zones with automatic handling of outages. See [Configure head node fault tolerance](https://docs.anyscale.com/administration/resource-management/head-node-fault-tolerance).\n",
        "\n",
        "\n",
        "For comprehensive guidance on production deployments, see the [Anyscale Services documentation](https://docs.anyscale.com/services) and [Ray Serve on the Anyscale Runtime](https://docs.anyscale.com/runtime/serve).\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "base",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.11.11"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 2
}
