py_test(
    name = "simple_example",
    size = "small",
    srcs = ["simple_example.py"],
    tags = [
        "compat",
        "exclusive",
        "team:ml",
    ],
    deps = ["//:ray_lib"],
)

py_test(
    name = "simple_tune",
    size = "small",
    srcs = ["simple_tune.py"],
    tags = [
        "compat",
        "exclusive",
        "team:ml",
    ],
    deps = ["//:ray_lib"],
)
