"""Platform-aware CI dependency resolution.

The Windows CI driver binaries (//ci/ray_ci:test_in_docker and
//ci/ray_ci:build_in_docker_windows) are non-hermetic py_binaries that execute on
the Windows agent's Python 3.8 conda base. On Windows their third-party deps must
therefore come from the Python 3.8 lock (@py_deps_windows, generated by
ci/raydepsets/configs/ci_windows.depsets.yaml). On every other platform they come
from the default @py_deps_py310 set.

ci_require() returns a plain alias label (e.g. //ci/ray_ci/deps:boto3) so it can be
used as an ordinary deps element. The per-platform select() lives inside that
alias (defined by ci_require_aliases() in //ci/ray_ci/deps). Use ci_require() in
place of the raw rules_python `requirement()` in any BUILD target that is part of
the Windows driver closure (//ci/ray_ci and //release).

Adding a new dep to that closure requires adding its name to WINDOWS_DRIVER_DEPS
below (and to release/requirements_windows.in so it lands in the lock).
"""

load("@py_deps_py310//:requirements.bzl", _require = "requirement")
load("@py_deps_windows//:requirements.bzl", _windows_require = "requirement")

# Every third-party package referenced via ci_require()/bk_require() in the
# Windows driver closure (//ci/ray_ci/BUILD.bazel and //release/BUILD.bazel).
# Each must exist in @py_deps_windows (release/requirements_windows.in).
WINDOWS_DRIVER_DEPS = [
    "aioboto3",
    "anyscale",
    "aws-requests-auth",
    "azure-identity",
    "azure-storage-blob",
    "bazel-runfiles",
    "boto3",
    "botocore",
    "click",
    "freezegun",
    "google-cloud-storage",
    "jinja2",
    "msal",
    "pybuildkite",
    "pytest",
    "pyyaml",
    "requests",
    "responses",
]

def _normalize(name):
    return name.lower().replace("-", "_").replace(".", "_")

def ci_require(name):
    """Return the per-platform alias label for pip package `name`."""
    return "//ci/ray_ci/deps:" + _normalize(name)

def ci_require_aliases():
    """Define one alias per WINDOWS_DRIVER_DEPS package, selecting the pip repo by platform."""
    for name in WINDOWS_DRIVER_DEPS:
        native.alias(
            name = _normalize(name),
            actual = select({
                "@platforms//os:windows": _windows_require(name),
                "//conditions:default": _require(name),
            }),
            visibility = ["//visibility:public"],
        )
