ARG BASE_IMAGE
FROM "$BASE_IMAGE"

ARG BUILDKITE_BAZEL_CACHE_URL
ARG BUILDKITE_PIPELINE_ID
ARG BUILDKITE_CACHE_READONLY

ENV BUILDKITE_BAZEL_CACHE_URL=${BUILDKITE_BAZEL_CACHE_URL}
ENV BUILDKITE_PIPELINE_ID=${BUILDKITE_PIPELINE_ID}
ENV BUILDKITE_CACHE_READONLY=${BUILDKITE_CACHE_READONLY}
ENV PYTHON=3.9
ENV RAY_USE_RANDOM_PORTS=1
ENV RAY_DEFAULT_BUILD=1
ENV RAY_INSTALL_JAVA=0
ENV RAY_ENABLE_WINDOWS_OR_OSX_CLUSTER=1
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8

COPY . .
RUN bash ci/ray_ci/windows/build_ray.sh

WORKDIR /rayci
